### ISSUE TITLE
一个gcc编译的问题。

### ISSUE THREAD

**Issue by glide-the** [CandyMi/cfadmin#1]
core.c:204:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
core.c:204:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
core.c:204:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/usr/bin/ld: /usr/local/lib/liblua.a(lstate.o): relocation R_X86_64_PC32 against symbol `lua_newstate' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: 最后的链结失败: 错误的值
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 1

不知道如何解决呢

**Comment by CandyMi** [comment]
@glide-the 请重新编译lua, 使用如下命令 ```make linux MYCFLAGS=-fPIC``` 然后重新 make rebuild

**Comment by CandyMi** [comment]
@glide-the 如果不是root权限, 请使用 ```sudo make build``` 或者 ```sudo make rebuild```

**Comment by glide-the** [comment]
已经解决，除了重新编译lua
make linux CFLAGS="-fPIC -DLUA_USE_LINUX"
并且
makefile gcc编译时     
   $(CC) core_start.c -o cfadmin $(MACRO) -ldl -lcore 
这一行 在ubuntu18下需要调换
   $(CC) core_start.c -o cfadmin $(MACRO)  -lcore -ldl

**Comment by CandyMi** [comment]
感谢反馈！ 这个兼容性问题已记录, 我会在master分支更新.
