### ISSUE TITLE
About  sendfile Support

### ISSUE THREAD

**Issue by CandyMi** [CandyMi/cfadmin#10]
考虑到`Lua`层面的`file:read` -> `sock:send`对大文件的发送会影响Lua虚拟机内存浮动的问题.

  之前的`httpd`库内部`static`相关资源为一次性读取完毕后组合发送`HTTP`头部与`HTTP`实体.

  现在改为先使用`sock:send`发送头部, 后使用`sendfile`实现`zero-copy`发送策略. 

  目前在`dev`分支已经修改完毕, 有兴趣的小伙伴可以帮忙测试!

![image](https://user-images.githubusercontent.com/13453599/63763538-7e1fc780-c8f7-11e9-992d-057c4406d0f7.png)

**Comment by gcclua** [comment]
great

**Comment by CandyMi** [comment]
目前已经合并到master分支.
