### ISSUE TITLE
Url path should be decode before ROUTE_FIND

### ISSUE THREAD

**Issue by gcclua** [CandyMi/cfadmin#11]
if my url is image has special character,  the image in static path will load fail

lualib/protocol/http.lua
PATH = UrlDecode(PATH)
local cls, typ = ROUTE_FIND(METHOD, PATH)

**Comment by CandyMi** [comment]
![image](https://user-images.githubusercontent.com/13453599/63997174-451e6780-cb30-11e9-82f4-efe2be8ad392.png)

I have modified and updated, the difference is that such modifications are only for `static` routes.

For this opportunity, I added a hard-coded `utf-8` for the `content-type` of the `static` resource.
