### ISSUE TITLE
有文件上传的例子吗

### ISSUE THREAD

**Issue by myfengstyle** [CandyMi/cfadmin#13]
有文件上传的例子吗

**Comment by CandyMi** [comment]
@myfengstyle 能详细描述一下你想怎么做么?

**Comment by myfengstyle** [comment]
后台图片上传

**Comment by CandyMi** [comment]
@myfengstyle 

您应该描述一下使用上传到七牛云的`OSS`还是上传到本地.

*  使用`cloud.qiniu`库的`oss/token`SDK生成token, 客户端拿token用form提交上传. 
    内部有API使用说明, 参考SDK使用与七牛云的文档即可知道如何上传.

*  本地上传可以直接用form提交. 使用`logging`可以打印`content`即看到上传文件内容.
    然后你可根据实际情况保存文件.

**Comment by myfengstyle** [comment]
好的，刚学习lua，建议写个例子，用的比较多

**Comment by CandyMi** [comment]
感谢您的建议. :)

**Comment by myfengstyle** [comment]
增加了吗

**Comment by CandyMi** [comment]
查看`script/test_upload.lua`

**Comment by CandyMi** [comment]
@myfengstyle 
补充了七牛sdk上传示例, 参考代码应该可以很快写出自己的demo.
