### ISSUE TITLE
ubuntu build error

### ISSUE THREAD

**Issue by exyoyou** [CandyMi/cfadmin#16]
@ubuntu:~/cdcore/core_framework$ make rebuild
********** Core library and executable **********
CC	-	libcore
CC	-	cfadmin
/usr/bin/ld: ./libcore.so: undefined reference to `sinh'
/usr/bin/ld: ./libcore.so: undefined reference to `log2'
/usr/bin/ld: ./libcore.so: undefined reference to `atan2'
/usr/bin/ld: ./libcore.so: undefined reference to `tanh'
/usr/bin/ld: ./libcore.so: undefined reference to `cosh'
/usr/bin/ld: ./libcore.so: undefined reference to `fmod'
/usr/bin/ld: ./libcore.so: undefined reference to `acos'
/usr/bin/ld: ./libcore.so: undefined reference to `sin'
/usr/bin/ld: ./libcore.so: undefined reference to `asin'
/usr/bin/ld: ./libcore.so: undefined reference to `exp'
/usr/bin/ld: ./libcore.so: undefined reference to `tan'
/usr/bin/ld: ./libcore.so: undefined reference to `cos'
/usr/bin/ld: ./libcore.so: undefined reference to `log'
/usr/bin/ld: ./libcore.so: undefined reference to `pow'
/usr/bin/ld: ./libcore.so: undefined reference to `log10'
/usr/bin/ld: ./libcore.so: undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:36：build] 错误 1
make: *** [Makefile:24：rebuild] 错误 2

请求大神 编译错误。

**Comment by CandyMi** [comment]
@yg-jiugui 

看错误提示应该是说没有链接math库, 这边提供下`ubuntu`的版本我测试看看.

**Comment by CandyMi** [comment]
@yg-jiugui 

您这边可以尝试将`src/Makefile`文件的27行添加`-lm`, 修改后的结果类似下面这样：

```bash
# 默认情况下使用系统内存分配器
CFLAGS += -Wall -O3 -fPIC --shared -fno-strict-aliasing -Wl,-rpath,. -Wl,-rpath,.. -Wl,-rpath,/usr/local/lib
# 修改之前
# DLL += -lev -llua -ldl
# 修改之后
DLL += -lev -llua -ldl -lm
MACRO += -w -O3 -Wl,-rpath,. -Wl,-rpath,.. -Wl,-rpath,/usr/local/lib
```

修改完成之后, 您尝试再次编译. 看是否还有这样的错误?

**Comment by exyoyou** [comment]
> @yg-jiugui
> 
> 看错误提示应该是说没有链接math库, 这边提供下`ubuntu`的版本我测试看看.

系统版本 Ubuntu 20.04 LTS 


修改 Makefile 文件后编译错误

如下：make build
********** Core library and executable **********
CC	-	libcore
CC	-	cfadmin
********** Built-in modules **********
CC	-	lsys
CC	-	ludp
CC	-	ltask
CC	-	ltimer
CC	-	laio
src/laio.c: In function ‘AIO_DONE_POLL’:
src/laio.c:341:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
  341 |   read(sp[0], &event, 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~
src/laio.c: In function ‘AIO_WANT_POLL’:
src/laio.c:335:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  335 |   write(sp[1], &event, 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~
CC	-	ltcp
src/ltcp.c:4:10: fatal error: openssl/ssl.h: 没有那个文件或目录
    4 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:30：internal] 错误 1
make: *** [Makefile:18：build] 错误 2

**Comment by CandyMi** [comment]
@yg-jiugui 

这边可以尝试使用`apt install libssl-dev`或者`apt reinstall libssl-dev`下载openssl依赖库.
