### ISSUE TITLE
自己编译和docker都不能正常运行

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#17]
ubutun 18
1. 文档说依赖libev 和lua 5.3 不够全面。必须依赖mysql，没有mysql 不能运行。
        是否可以考虑多数据库支持？luasql 这样的。
2 .git 下载后编译，编译有错误：
         1）. lua 不能正确连接 math库
         2）. 路径一定在usr /local.. 下找，非root用户有些麻烦，交叉编译不行。
         3）. 没安装打包。
3.  运行时总是连接mysql 出问题。几分钟就近**1G**日志。手动连接mysql，都没有问题。

4. 更换docker 
         运行：docker-compose -f docker-compose-with-cfadmin.yaml up
         出现两种错误：
         1） mysql 冲突，这个停掉主机mysql 可以暂时解决
         2） 同样一直连接mysql。 日志如下：

root@testu:/mnt/work/core_framework/docker# docker-compose -f docker-compose-with-cfadmin.yaml up
Starting docker_WebDB_1 ... 
Starting docker_WebDB_1 ... done
Starting docker_WebApp_1 ... 
Starting docker_WebApp_1 ... done
Attaching to docker_WebDB_1, docker_WebApp_1
WebDB_1   | 2020-07-15 06:06:53+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.49-1debian9 started.
WebDB_1   | 2020-07-15 06:06:54+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
WebDB_1   | 2020-07-15 06:06:54+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.49-1debian9 started.
WebDB_1   | 2020-07-15 06:06:55 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
WebDB_1   | 2020-07-15 06:06:56 0 [Note] mysqld (mysqld 5.6.49) starting as process 1 ...
WebDB_1   | 2020-07-15 06:06:56 1 [Note] Plugin 'FEDERATED' is disabled.
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: The InnoDB memory heap is disabled
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Memory barrier is not used
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Using Linux native AIO
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Using CPU crc32 instructions
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Completed initialization of buffer pool
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Highest supported file format is Barracuda.
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: The log sequence numbers 1625987 and 1625987 in ibdata files do not match the log sequence number 1625997 in the ib_logfiles!
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Database was not shutdown normally!
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Starting crash recovery.
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Reading tablespace information from the .ibd files...
WebDB_1   | 2020-07-15 06:06:56 1 [ERROR] InnoDB: space header page consists of zero bytes in tablespace ./cfadmin/cfadmin_headers.ibd (table cfadmin/cfadmin_headers)
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size:1024 Pages to analyze:64
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size: 1024, Possible space_id count:0
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size:2048 Pages to analyze:32
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size: 2048, Possible space_id count:0
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size:4096 Pages to analyze:16
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size: 4096, Possible space_id count:0
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size:8192 Pages to analyze:8
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size: 8192, Possible space_id count:0
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size:16384 Pages to analyze:4
WebDB_1   | 2020-07-15 06:06:56 1 [Note] InnoDB: Page size: 16384, Possible space_id count:0
WebDB_1   | 2020-07-15 06:06:56 7fdd85f79040  InnoDB: Operating system error number 2 in a file operation.
WebDB_1   | InnoDB: The error means the system cannot find the path specified.
WebDB_1   | InnoDB: If you are installing InnoDB, remember that you must create
WebDB_1   | InnoDB: directories yourself, InnoDB does not create them.
WebDB_1   | InnoDB: Error: could not open single-table tablespace file ./cfadmin/cfadmin_headers.ibd
WebDB_1   | InnoDB: We do not continue the crash recovery, because the table may become
WebDB_1   | InnoDB: corrupt if we cannot apply the log records in the InnoDB log to it.
WebDB_1   | InnoDB: To fix the problem and start mysqld:
WebDB_1   | InnoDB: 1) If there is a permission problem in the file and mysqld cannot
WebDB_1   | InnoDB: open the file, you should modify the permissions.
WebDB_1   | InnoDB: 2) If the table is not needed, or you can restore it from a backup,
WebDB_1   | InnoDB: then you can remove the .ibd file, and InnoDB will do a normal
WebDB_1   | InnoDB: crash recovery and ignore that table.
WebDB_1   | InnoDB: 3) If the file system or the disk is broken, and you cannot remove
WebDB_1   | InnoDB: the .ibd file, you can set innodb_force_recovery > 0 in my.cnf

**Comment by CandyMi** [comment]
@suzaichuan  首先! 感谢您使用cf框架, 并且给予这么细致的问题描述. 

这边回答下您的疑问:

---

  * Q. `文档说依赖libev 和lua 5.3 不够全面。`

  * A. 最新的版本依赖libev、libeio、lua、openssl、zlib等库, 您这边可以参考下`docker/Dockerfile`内的安装流程.

---

  * Q. `必须依赖mysql，没有mysql 不能运行。是否可以考虑多数据库支持？luasql 这样的。`

  * A. 目前由于个人精力有限, 只能先完成非阻塞的mysql数据库客户端与redis客户端. luasql由于使用外部阻塞连接, 目前暂时无法高效移植到框架内.

---

  * Q. `运行时总是连接mysql 出问题。几分钟就近1G日志。手动连接mysql，都没有问题。`

  * A. 这边指出的连接问题, 应该是在运行时停止了mysql吧. 日志数量多可能是由于mysql连接池一直在尝试重连. 停止mysql之后建议cf进程也停止.

---

  * Q. `更换docker出现了两种错误`

  * A. 这两种错误看起: 要么是镜像损毁, 要么是更新docker后导致的兼容问题. 建议不要轻易在运行时更换docker版本.

**Comment by CandyMi** [comment]
@suzaichuan 

某些`linux`发行版的`gcc`并包含`math`库, 这已经在`dev`分支测试过了. 已经增加了`-lm`的编译参数.

目前已经合并到了`master`分支, 这边可以`pull`最新代码测试.

**Comment by suzaichuan** [comment]
@CandyMi 
非常感谢热心回答。
1.   os： ubutun 18 server 全新版本，在这个基础上安装的docker；没进行任何更换版本动作。安装后运行的docker-compose -f docker-compose-with-cfadmin.yaml up 也没有没进行任何配置动作。
    有个前置的过程，就是主机上编译运行，发现无法运行才使用的docker试试的。
2. 多数据库的，你可以将mysql使用的接口封装在一个文件里，接口固定，引用单一，换库的话，用户只要实现接口功能就可以了。
3. 日志打印，三五次连接不上或者错误明显，只要不改配置永远连不上的情况。不应该再去无效动作。

安装使用文档可以再加强一些，尤其默认配置这块。这样方面使用。项目非常优秀。可以考虑放到openwrt下，这样就得考虑lua5.1。

**Comment by suzaichuan** [comment]
mysql5.7.3：
默认信息 root 用户密码123456789: 
mysql> update mysql.user set authentication_string=password('123456789') where user='root';
mysql> delete from mysql.user where user='';
mysql> flush privileges;
mysql> CREATE DATABASE cfadmin;
mysql> use cfadmin;
mysql> source /mnt/core_framework/lualib/admin/db/database.sql;
以上可以解决了编译安装的运行问题。
然后访问http://ip:8080/admin/ 可以访问。

发现，网页显示的速度并不快，有明显的延迟。
同样网络及条件下，数据库数量很少，用nginx+lua layui ，速度明显（postgres库）。sqlite3 也非常明显的速度；有空换mysql试试。

admin下 有两个地方需要修改；
      1.添加菜单，不能立即刷新左侧；需要手动切换页面后才行。
      2. 语言切换，汉语应该永远”汉语”，英语应该永远english，以便看不懂其他语言的人误点，后能够回来。

**Comment by CandyMi** [comment]
@suzaichuan 

感谢您的测试反馈! 

  1. 关于DB/Cache的连接池之前有考虑过做成X -> Y次连接之后不再尝试, 但是这会涉及到另外的问题: 多少次合适? 如果设置永久重试？
  事实上! 无论数据库宕机还是有意的用户定期重启维护, 框架在这种情况下也是无法得知后端的真正意图. 不断的重试反而能最好的现场保留痕迹.

  2. 理论上我在编写`admin`库的时候已经考虑过更换数据库了, 如果定制数据库则直接实现`admin.db`内的所有实现即可. 


  3. 由于个人工作原因, 我可能没有很多的精力去维护大量的`lua`库. 如果有可能的话, 我会非常欢迎贡献代码.

  4. 我不对`lua5.3`与其之前的分裂社区看好, 同时也不想为其做大量的代码兼容性工作. 这是为了让框架更加与时俱进（同时为`lua 5.4`的跟进做准备）.


关于您这边提到的一些反馈, 我有一些疑问:

  1. `发现，网页显示的速度并不快，有明显的延迟。同样网络及条件下，数据库数量很少，用nginx+lua layui ，速度明显（postgres库）。sqlite3 也非常明显的速度；有空换mysql试试。
  `

  * 您这边说的速度不快, 我无法知道具体情况. 如果有可能的话, 您可以调试看下是框架内部处理过慢, 还是网络连接的延迟导致的.

  2. ```添加菜单，不能立即刷新左侧；需要手动切换页面后才行。```
  
  * 我也考虑了这个问题, 目前的解决方法是在菜单`添加完成`之后的页面调用`parent.location.reload() `. 不知道您是否有更好的想法?

  3. ``` 语言切换，汉语应该永远”汉语”，英语应该永远english，以便看不懂其他语言的人误点，后能够回来。```

  * 我个人认为这违背了语种显示的统一性原则,  ！如果这个理由不够充分, 我们也可以这样设想一个场景: 

  * "一个X国人不懂Y国的语言, 它不可能去尝试切换Y国语言的语种界面的. 即使误操作了, 也可以由开发、测试人员来协助修改回来. 因为任何点击切换语种的人, 从本质上来说都是至少掌握了基础多语种水平."

  * 顺便提一句: 如果仅仅开发单语种的后台, 可以在代码内配置下面的内容，这样可以防止误操作   :)  

  ```lua
  -- dashboard页面不显示切换语言
  admin.display_lang(false)
  -- 设置默认的区域语言, 默认为: ZH-CN
  -- cfadmin.set_locale('EN-US')
  ```

**Comment by suzaichuan** [comment]
@CandyMi  
    1. lua 兼容问题，大多都是5.1的尽管5.3 很好，就如你的问档说的jit 一样。5.1 很多用户，庞大的openwrt群体，都是5.1使用。基本流行的lua框架都兼容5.1 。
    2.网页显示慢的问题：后台看 cpu闲的很，具体的没有去分析代码。网速的问题不用考虑，相同网段及甚至ip都一样；虚拟机快照切换。现象感觉到延迟，仅此而已；与访问量等都没关系。
   3. 添加菜单问题。具体的没有去细看你的实现方式。但直观感觉与layuimini 的多tab一样的，与其自己再去写前端适配，不如直接引入layuimini；没有必要全部更新，只要局部更新就可以了；最简单直接添加元素到菜单导航。下次有刷新动作时再去后台获取数据刷新。
   4.多语言的，我很不认同你的观点。你可以看安装linux选择语言，去银行看ATM语言切换，都会发现，中文永远“中文”，英文永远English。 因为你满屏都可以不认识，唯独自己的语言的自必须认识，这样才能切换回来。同样，你看看你的手机，尤其老式的诺基亚。
  5. 数据库连接不上的原因，很直接，是不可能做到智能化的。不过可以参考中国电信标准：一般心跳10次，失败进行倒换备用。如果没有备用或者备用也无法使用，有个配置项failed_expire; 就是失败了多久再去尝试，这个值一般是半小时。
 6.同样，由于时间的限制，还没来得及细看实现过程。但基本可以确定，这个项目依赖极小，可以裁剪到嵌入式设备中，这是非常大的优势，不足就是lua的兼容性需要继续评估。

**Comment by CandyMi** [comment]
@suzaichuan  您这边反馈的情况, 这两天我仔细的时候思考了一下:

  1. 性能方面我觉得它并不会有问题(至少我没测试出来), 我更建议的是根据实际情况深入定制优化. 因为我自己在公司项目上使用的时候也是如此.

  2. 我思考了`新增菜单的自动完成和手动完成刷新`需求. 由于采用`iframe`的实现让父级窗口刷新会丢失子窗口内容, 虽然有方法可以保存但做起来并不优雅. 也许出现更好的更新流程建议, 会使我更快的将这个`feature`完成. 并且我当初的选型是`x-admin`, 所以这可能也会对最终实现有一定影响.

  3. 对于中、英文切换的那个论点, 我认为建议很好(并且我也去`ATM`机上试过了). 但是由于我提供了手动对`locale`的修改支持, 所以我想留给大家有需要自行修改了.

顺便一提:

  * 最近您提出的连接池的问题, 我已在主线分支修改为`每次连接出错3秒后再次尝试连接`. 这样应该会缓解DB日志堆积的问题.

**Comment by suzaichuan** [comment]
尝试做了一下兼容性编译。发现 lz lfs lffi lpbc lpeg lcrypt lcjson lmsgpack lhttpparser 几个模块根本就不依赖core。分两步：
1. core及sys  udp... 这些用到了core的，使用 lua-compat-5.3 编译通过。
2. 第三方的库，全部被修改了，按道理官方应该都做了兼容处理。
    直接改一下引用，去掉core.h 换成lua的，编译也没太大问题。就是lz一直运行不起来。应该lz改动很大。
    对于lua文件，用到了位运算，将&| ^ << >> 等换成lua的函数，可上下兼容。

用以上修改在lua5.3 下没有问题。 这样得出结论：
1. 第三方库，暂时发现lz 兼容处理有问题。
2. 整个项目，无可选项，即所有列出的库，必须有。很多场景用不到那么多，应该可选择加载。比如ssl，有的项目不需要，编译时没必要依赖。

lua 5.1 还是因为lz 运行不起来。不只是否有可选项，不启用lz等。

**Comment by CandyMi** [comment]
lz库目前在这些地方有依赖:

 * `httpd`开启`gzip`支持的时候会需要; 不开启的情况下可以在`protocol/http/init.lua`可以取消引用.

 * `httpd`的ws路由注册后的握手如果需要`permessage-deflate`支持也会用到lz库, 可以自行修改不进行握手就不会使用到.

 * `httpc`库发送请求到服务端可能会强制返回`gzip`后的`response`. 如果你不需要`httpc`或者能保证不会用到`gzip`可以取消引用.
 
值得说明的是: `zlib`库与`ssl`库在非嵌入式web开发中都是强制依赖的.

**Comment by suzaichuan** [comment]
@CandyMi 

非常感谢！
我估计要去看看代码处理了。不过ssl的问题，这个问题很复杂（openssl,MBEDTLS,POLARSSL），chrome高版本很多场景确实限制了必须使用。但还是留出了配置可以越过s的使用，只是提醒这样不安全。zlib，恰恰很多嵌入式要求使用，为了节省带宽。不仅要压缩，http类似字符串协议还要缩写比如请求T，响应P，应答K。这些，不可能全部支持的，也不可能全部考虑到；所以开关控制，留给场景自用是最好的选择。

建议把项目功能分开解耦一下。 
1.http服务的 功能，项nginx一样，可以选择启用gzip，log 等等
2.各种协议 同1，这个功能很好，最好解耦。
3. 应用服务
4.数据存储。
