### ISSUE TITLE
安全机制控制问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#19]
hi
经过使用，发现对客户端信息缺失地址和端口。建议默认提供接口查询本次消息，谁发来的；或者加入消息中。
使用场景： 
          1. 安全机制，非法访问的来源，加入黑名单
          2. 物联网，根据客户端ip 端口，映射设备身份，不需要额外增加应用层消息。

**Comment by CandyMi** [comment]
@suzaichuan 

  `httpd`服务中的`content`包含了客户端的IP地址, 建议以此为参考依据进行测试.

  如果想阻断指定的黑名单IP或列表, 这个需要自行根据`before`设计过滤方法.

**Comment by suzaichuan** [comment]
ok
