### ISSUE TITLE
为什么不基于libuv呢, 这样还能把windows也支持了

### ISSUE THREAD

**Issue by dwing4g** [CandyMi/cfadmin#2]
何况libuv有node.js这样的流行的框架在用, 性能和稳定性更有保障.

**Comment by CandyMi** [comment]
> 何况libuv有node.js这样的流行的框架在用, 性能和稳定性更有保障.

libev更精简, libuv 回调层次更加深入.  不容易维护底层代码.
同时封装api时候维护成本会增加, 不易阅读代码.

**Comment by CandyMi** [comment]
@dwing4g
至于windows 原生支持, 没那么大的需要. 毕竟开发者都或多或少使用Unix like 或 BSD 操作系统.

**Comment by dwing4g** [comment]
@CandyMi 
Windows现在仍然算很大占有率的系统了, 当然确实有很多偏服务器的框架不考虑Windows可以理解, 但我仍然觉得全平台的支持对开发者最友好.
我找到一个Lua+Libuv的框架, 貌似抄了node.js的设计, 供参考吧: https://github.com/luvit/luvit

**Comment by CandyMi** [comment]
@dwing4g 
准确来说luvit是基于luajit + libuv的开发框架.
最早在cf开发之初, 曾经有一个草稿版本是基于luajit与libuv. 但在之后的设计中逐渐发现: 
  * libuv回调的深度与过多的(cf底层的C)API封装直接造成cf代码阅读成本与维护成本线性增加, cf目的是为使用者提供轻量级、易维护、高可读性的lua网络开发框架.
  * libuv 将一些过于底层的API封装到到内部, 这样会造成需要开发一些定制库需要提供一些难以阅读的代码与hook的写法来完成. 这样对cf的维护也是非常不友好的.
  * 在调试时经常发现在luajit jit trace时经常会中断, 在使用jit库打印后发现luajit在频繁的lua与Lua C API切换到时候造成了jit miss.

基于以上考虑, 所以未曾使用相关libuv与luajit.
而可以肯定的是libuv绝对是一个较为优秀的C事件驱动库, 同时Luajit作为lua的一个即时编译器提供了较为原版更加优秀的运行时.
同时非常感谢您对cf支持Windows如此在意, 毕竟在草稿版选择考虑libuv也是因为对全平台支持也在当初考虑范围内. 但是cf提供了Docker版, Windows进行开发也不是难事.

**Comment by dwing4g** [comment]
@CandyMi
频繁跨语言边界确实会导致性能问题, 我觉得回调的问题可以直接在C这层解决, 封装好的话, 跨边界调用可以尽可能的少,每次调用做的事尽可能的多, 而且给上层仍然可以是无回调的reactor模式. 当然接口抽象得好的话, 底层的C库还可以很方便地更换.

**Comment by CandyMi** [comment]
@dwing4g 
您说的非常正确!
举一个最经典的示例: Accept callback -> receive callback -> send callback -> ... -> close(socket)
在我们最经典的reactor并发模型中的开发顺序应该是这样的:
  1. server监听了一个socket, 创建Accept IO等待链接;
  2. 调用accept一个创建一个client socket;
  3. 监听client socket read IO事件;
  4. read IO回调触发, handle client socket相关操作;
  5. 调用send 回应请求数据;
  6. 回到第三步或close client socket;

但是在上述的场景的第四、五步中, 遇到了如下问题:
  1. send/read如果需要直接尝试发送/读取数据不用在底层注册IO事件呢?
  2. 那send回调后的send buf回调呢？

解决办法:
  1. 第一个问题的解决方案是越过相关库直接操作底层API(cf就是这么做的). 这样显著减少了API交互次数.
  2. 第二个解决方案显然需要更多的代码来适配不同驱动库, 还是前面说的适应库的同时也要适应平台.

最后, cf对使用者提供的是一种'同步非阻塞'的开发方式并将异步与回调隐藏在框架层.
对比一些框架单纯提供一些回调嵌套库, 这样的开发逻辑更加直观明确.

**Comment by dwing4g** [comment]
@CandyMi 
另外还想起一个问题, 就是官方Lua本身由于Lua和C的边界隔离, Lua的string和C的数据很难有效地交互, 拷贝一次恐怕不可避免,Lua对string还要做hash和唯一化, 不拷贝则需要频繁的C接口调用,可能性能更糟.
此处也许只有LuaJIT的ffi可解, ffi可分配C层能共享且直接访问的缓冲区, 然后在Lua这边也能依赖JIT高效地访问数据.

**Comment by CandyMi** [comment]
@dwing4g 
您说的这个应该是涉及Lua string的在vm中的实现或不同宿主语言交互存在的问题.
首先, 关于字符串对于send/read buffer的双向拷贝肯定是难以避免的. 同时, 一些lua开发者都尽量减少string创建、销毁、拼接来避免内存占用与性能上的问题.
其次, luajit通过一些api动态的创建C层string(char *)类型本身会增加生命周期管理成本, 而luajit的```ffi.C.malloc``` ```ffi.C.free```都是为此存在的.
个人觉得这些问题不用过于担心, 就如同OR、Skynet等使用的时候都不会考虑太多字符串操作性能消耗. 
毕竟在实际使用cf、luvit来进行开发的时候, 使用者很少会只使用单cf server实例的. :)

**Comment by CandyMi** [comment]
@dwing4g 

cf的docker文件夹内提供了dockerfile与docker-compose文件.

在Windows上编写代码进行[开发、测试、演示](https://github.com/CandyMi/core_framework/wiki/cfadmin)已经不再是难事了. 

我相信已经解决了此问题, Windows原生支持也许不再是那么必要!

相信您如果对它是真爱, 就应该能理解它. :)
