### ISSUE TITLE
文件上传只能小文件

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#20]
文件上传10M 文件 就不能上传了，负载等于1024*1024 也是不行的。

**Comment by CandyMi** [comment]
@suzaichuan 

默认情况下,框架是不允许上传超过1M大小的文件内容的.  大文件的碎片化上传在`lua`内部是非常消耗内存的.

当然如果你确定需要使用的话可以从下面的文档中获得信息！`1024 * 1024`的单位是`字节`, 也就是说实际是`1M`.

我建议配置在有负载均衡器的情况下, 在负载均衡器前面先配置`body_size`为15M; 然后再httpd这边配置`15 * 1024 * 1024`;

关于更多详细的配置, 我在[文档](https://doc.cfadmin.cn/library/httpd/#4-httpdmax_body_size)有说明.

**Comment by suzaichuan** [comment]
@CandyMi  
实际上 小于 1024 * 1024 ；能传的 比body_size 配置的实际小 几十个字节。

**Comment by CandyMi** [comment]
@suzaichuan 
是的! 所以建议约束数值的不要过于`严谨`, 给出一定预留空间较为合适.

**Comment by suzaichuan** [comment]
下载文件时，存在这问题：
浏览器下载文件，content-type 返回会被改掉：use 返回text，api 返回json。
返回的文件总是被网页打开，而非文件保存。用代码ajax 保存，浏览器还会限制。
所以应该默认返回原有的类型，路由处理回调可以修改返回类型就可以了。

**Comment by CandyMi** [comment]
> 下载文件时，存在这问题：
> 浏览器下载文件，content-type 返回会被改掉：use 返回text，api 返回json。
> 返回的文件总是被网页打开，而非文件保存。用代码ajax 保存，浏览器还会限制。
> 所以应该默认返回原有的类型，路由处理回调可以修改返回类型就可以了。

`USE`路由返回`text/html`,`API`路由返回`application/json`这就是规定好的. 用户自行根据情况选择即可. 

假设你需要返回一个文件内容(例如在`API`或`USE`路由内返回`.csv`后缀的文件), 那么我建议你用下列方法实现:

* 首先将内容存储到文件并命名后缀为`.csv`格式;
* 然后将静态文件路径拼接好后返回给请求者;
* 请求者根据拼接地址再次发起静态文件请求;

**Comment by suzaichuan** [comment]
静态文件路径好像只能注册一个，js，css等需要；而这些文件都属于程序，在安全区域内；
提供下载的文件路径在其他地方，用静态方法不太方便获取。

**Comment by CandyMi** [comment]
如果是对文件需要强控制访问的, 一般都需要额外的程序来保证.

例如某些项目用户身份证验证都是用的云服务的`OSS`来做鉴权访问、某分布式文件系统服务集群来完成. 

当初不允许控制`静态文件访问`的原因也是在这个考虑范围的; 因为它做某些功能天生就会不合适, 即使提供了功能也会缺更多的组件难以成为`可用的feature`.

同时, 一些同学也会我提供了某个特性而会不小心`误用`. 例如: 将海量图片存储在本地而不是专门存储的服务器上.  

因此干脆不提供这个功能, 这样反而能让大家更加灵活的组合所有脚手架.

望理解. ：）

**Comment by suzaichuan** [comment]
是的，额外控制，自定义处理读写文件；但浏览器无法修改，数据是拿到了就是无法保存到本地，用curl 等手段均ok。
只要能保证content-type，浏览器就ok了。

**Comment by CandyMi** [comment]
@suzaichuan 那你的需求是怎么样的呢？

**Comment by suzaichuan** [comment]
@CandyMi 
需求很简单： 就是把上传的文件可以下载下来。或者把日志文件下载下来。
页面选中文件点击下载时，文件在页面打开了，并没有保存。
其原因是 请求携带 类型 application/octet- stream，不管用use还是api都会被修改。

**Comment by CandyMi** [comment]
@suzaichuan 你的实现代码发一份我看看.

**Comment by suzaichuan** [comment]
local aio = require "aio"
local aio_open = aio.open

local function read_file(path)
    local f, err = aio_open(path)
    if not f then
      return nil, err
    end
    local content = f:readall()
     f:close()
     f = nil
     return content
end
function boot:get()
   local filepath=tconfig.filepath or "/tmp/"
   if(self.args) then
       local typef=self.args['t']
       local filename=filepath..(oid or "")
       if(typef=="ls") then
                local res = tconfig.forksync(attrdir,filename)
                return json.encode({code=0,msg= "",data=res})
       elseif(typef=="down") then
          return  read_file(filename)
       end
   end
   return '{"code":404,"msg":"failed"}'
end

**Comment by CandyMi** [comment]
你的需求和代码我已收到并且了解.  目前已经进行了修改, 你拉取最最新分支测试一下.

未被记录在`mime.lua`中的后缀名都会提示下载, 你可以写入一个`xxx.log`的文件进行尝试.

**Comment by suzaichuan** [comment]
好的，我来测试一下。
我也将修改的都发给你check一下，看看是否需要合入：
1.数据库 增加sqlite支持，启动main driver 标识数据库类型 ，sqlite mysql 测试ok，postgres 还没测试
2. 编译修改，可以支持嵌入式编译，不仅仅x86 （x86 实际使用中存在openssl 版本兼容问题 ）
3.路由前缀匹配  /remote/api/abc => 进入/remote/api 路由
4. 增加环境变量支持： 1） luapath 支持； 2）启动数据库及监听端口（不重要）
[cfadmin_patch.zip](https://github.com/CandyMi/cfadmin/files/5740887/cfadmin_patch.zip)

**Comment by CandyMi** [comment]
@suzaichuan 欢迎以`pr`的形式, 这样我们能针对性的讨论
