### ISSUE TITLE
域名访问 出现问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#21]
1. curl 访问发现的问题
测试时
curl 192.168.0.111/admin/a 是ok的
curl  www.example.com/admin/a -x192.168.0.111:80 是不行的
curl  192.168.0.111/admin/a  -x192.168.0.111:80 是不行的
等等，用了代理都不行 都是404
2. 访问 admin/a  不返回，下次无法访问的问题，还没解决。

**Comment by CandyMi** [comment]
@suzaichuan 

感谢你的反馈!

你这边提到的curl进行测试, 我这边无法判断你想测试什么结果. 所以我必须与您沟通以下问题:

  * 你这边使用`curl 192.168.0.111/admin/a`命令来说明此服务器可用并且有`/admin/a`的路由.

  * `curl www.example.com/admin/a -x192.168.0.111:80` 我的理解是你将192.168.0.111:80服务器作为http connect代理使用.

  * `curl 192.168.0.111/admin/a -x192.168.0.111:80` 我的理解是你将192.168.0.111:80服务器作为http connect代理使用并且访问服务器本身.

假设`192.168.0.111`主机`80`端口的`web`服务是由`cf`框架的`httpd`实现, 那么我需要说明的是`httpd`服务器不支持`connect`的`METHOD`.

如果我的判断是错误的, 那么您在提出下一个疑问前可以附上curl命令加上`-v`参数来打印连接过程以获得更多信息方便后续疑问沟通.

**Comment by suzaichuan** [comment]
是的，服务器监听 192.168.0.111:80 ； 消息也是向192.168.0.111:80 发送的。只是消息的url host 是域名或者公网IP信息。
此用法主要是dongle 内外网的安全机制处理不一样，访问url 是固定的。

**Comment by CandyMi** [comment]
很可惜，`cf`框架的`httpd`服务是无法识别代理请求的.

**Comment by suzaichuan** [comment]
非常感谢！ 
只能额外办法解决了。
再问一个问题  路由使用 /remote/%w+ ，发现无法匹配？正确的格式语法是什么样的？

**Comment by CandyMi** [comment]
@suzaichuan 

可以参考这里让框架支持[REST路由语法](https://doc.cfadmin.cn/library/httpd/#15-httpdenable_rest).

**Comment by suzaichuan** [comment]
非常感谢！
remote/{string:id}  访问 remote/w 是ok的 但 remote/{string:did} 访问  remote/w 就不行
如果是
url: /remote/a/b/c/d 这种？
 使用 /remote/{string[]:slist}。 访问 remote/w ok ，但remote/w/c/d/d 不行 remote/w/c 也不行
换成/remote/{string[]:{a,b,c,d}} 也不行
是不是不支持多级？

**Comment by CandyMi** [comment]
目前只支持文档上描述的语法.

**Comment by suzaichuan** [comment]
nginx   /a 和 /a/ 路由是不一样的。是否可以考虑一下这种路由机制？而  rest enable 这种语法，提取变量，其实质意义不大，需要的会根据自己实际去解析。
我目前临时解决方案是，在路由查找的find 中，routes 中如果没有，增加一个else分支，取根目录查找（比如/remote）。
然后使用 app:use('/remote', function (content)  ... end）；试图app:use('/remote/', function (content)  ... end）发现都不能成功。

还有一个问题，上次问过的nat 穿透的问题，content中只有clientip 但没有port端口，无法区分访问者。是否有办法获取到访问者的端口？

**Comment by CandyMi** [comment]
1. 框架内部不考虑有路由`Group`的情况, 因为这可以被用户侧加上前缀(`prefix`); 框架早就提供了`group`方法, 只是后期准备去除掉. 

```lua
function httpd:group(target, prefix, array)
    assert((target == self.API or target == self.USE) and type(prefix) == 'string' and type(array) == 'table' , "注册路由组失败")
    for _, route in ipairs(array) do
        local r, c = route['route'], route['class']
        if target == self.USE then
            self:use(prefix .. r, c)
        else
            self:api(prefix .. r, c)
        end
    end
end
```

  从上述实现代码可以看出! 这是任何人都可以在外部轻松实现的, 但是如果交由框架来实现反而影响灵活性.

---

  2. `/a` and `/a/`是同一个路由这个是无争议的, 并且框架实现的就是标准兼容的写法; 我们认为减少写兼容代码的难度, 专注于业务代码实现会更好.

```lua
api:api("/a", function( content )
  ...
end)
```

  所以, 我们认为只有其它类型的产品才会需要思考这样的问题! 例如: 代理服务器， 负载均衡器等等.

---

  3. `rest`语法就是一种标准与规范. 不是意义大不大的问题, 而是解决特殊情况下的问题而存在的:

```lua
api:api("/api/user/{number:uid}.html", function( content )
  ...
end)
```

  运营对页面进行`静态化`展示并减少`query`出现在浏览器上, 这对web开发者来说是非常重要的场景. 否则你必须手动生成静态页面来完成, 这将会限制框架的使用场景.

---

  4. 无论是`ip`or`port`都无法真正有效区分用户, `ip` and `port`只是用来区分来源. 特别是内部使用`unix domain socket`的时候.

**Comment by suzaichuan** [comment]
1-2 .非常赞同对路由的看法。我就是解决一个简单代理的问题。因为提供了httpc，一些特殊的访问，远程获取页面到本地，又不仅仅是代理。所以需要处理。这对网管系统非常重要的功能。如果加一个nginx ，依然要实现逻辑，两套框架，有点冗余。所以才会提出对路由的处理问题。根据前缀区分本地还是远程的。当然实际处理确实会麻烦一些，cookie等的处理。
3. 至于restful的问题，的确存在这种场景，但这种场景是完全可以手动实现的，毕竟提供了path，这都不是问题。这种语法有点像flask的路由。
4. ip 和端口 特定场景下完全可以区分用户的。经过NAT，同一局域网下的clientip 映射成完全一样的了，无法区分出具体的设备（设备都是bind端口的）。除了专网，其他的网络基本都是局域网组网再出局。目前我的解决方案是额外增加一个程序，来处理设备连接。如果cf能获取端口，就不需要这个程序了。
   还有专门的网络设备，需要根据断源与 目的来进行处理。cf小而轻便，非常适合，而且也很容易。

**Comment by CandyMi** [comment]
@suzaichuan 

虽然我还对你提出的业务需求存在疑问, 但是我觉得应该尊重各种业务场景  : )

我决定在`httpd`中为`content`提供`client_ip`与`client_port`两个属性用来完成你的需求, 不知道这样能不能解决你说的业务场景问题?

**Comment by CandyMi** [comment]
@suzaichuan 

但是这种情况不适用于`unix domain socket`, 因为它本身就没有`port`

**Comment by suzaichuan** [comment]
@CandyMi 
没明白domain socket的意思？
我所接触的domain 用法。依然是可以绑定端口的。 电信的 DNS 可以配置对应的端口；很多不配置端口的DNS 获取多个ip地址进行主备的，依然要绑定端口，企业用户还要指定子接口。
对于分权分域的，依然是这些用法。
从linux scoket 上看 用file名起socket 实质上是管道，无法跨设备的。其他的都不存在没有端口的。

**Comment by CandyMi** [comment]
```lua
app:listen_ssl("0.0.0.0", 443, 256, "web.key", "web.cert")
app:listen("0.0.0.0", 9999)

-- app:listenx("/var/run/web.sock", 1024)

app:run()

```

所谓的`unix domain socket`就是`IPC`.  这是为了优化与负载均衡器之间联系存在的。

**Comment by suzaichuan** [comment]
是的 /var/run/web.sock 的确是无法知道客户端。这种用法是前面有个代理服务器，代理会知道的。

另外遇到一个问题，Content-Type 如何修改指定呢？

**Comment by CandyMi** [comment]
目前不支持修改`Content-Type`

**Comment by suzaichuan** [comment]
app:before(function (content)
   print("---------------bbbbbbbbbbbbbbbbbbbb")
end)
app:use('/remote', function (content)
        return "======="
end)
始终进入不了 before ？是有什么设置么？

**Comment by CandyMi** [comment]
刚刚确认了你说这是个`bug`, 一个参数命名错误导致没有调用. 最近更新的时候可能被测试到.

今晚我会将这个`bug`修复并且与前面提到的`client_port`更新代码主线代码.

**Comment by CandyMi** [comment]
@suzaichuan 

目前在master分支已经更新了最新版本的代码, 可以用下述代码进行测试:

```lua
app:before(function ( content )
  require "utils"
  var_dump(content)
end)
```

```bash
[candy@MacBookPro:~/Documents/cfadmin] $ ./cfadmin
[2020/12/16 20:59:06] [INFO] httpd listen: 0.0.0.0:9999
[2020/12/16 20:59:06] [INFO] httpd Web Server Running...
{
      ["ROUTE"] = "USE",
      ["method"] = "GET",
      ["client_ip"] = "::1",
      ["client_port"] = 7912,
      ["headers"] = {
            ["Host"] = "localhost:9999",
            ["Accept"] = "*/*",
            ["User-Agent"] = "curl/7.64.1",
      },
      ["path"] = "/admin",
}
[2020/12/16 20:59:10] - ::1 - ::1 - /admin - GET - 401 - req_time: 0.000230/Sec
```
