### ISSUE TITLE
firefox 认证不正确

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#22]
使用admin 登录；chrome下没任何问题；
换成firefox，登录成功后又返回登录界面，死循环。
抓包看了一下，firefox在登录成功后的admin/dashbord 请求中cookie 只有CFLANG，没有CFTOKEN
换了几个firefox版本均是如此。

**Comment by CandyMi** [comment]
你提到的问题，我这边无法复现. 测试用到的版本如下图所示。

![image](https://user-images.githubusercontent.com/13453599/102176034-8ed4c200-3edb-11eb-8588-ea1091cf85de.png)

**Comment by CandyMi** [comment]
这边有一种可能是您那边的代码没有更新, 可能会因为一些兼容性问题导致cookie没有正常解析与发送.

您这边可以尝试使用最新版本的代码构建, 如果还是有问题的话可以持续回复我这边.

**Comment by suzaichuan** [comment]
好的 非常感谢！ 
         找到问题了，将 PC 的时间提前就会复现问题。服务器ntp 没有同步导致的。chrome 可能不关系时间 而没有问题。
