### ISSUE TITLE
浏览器适配问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#23]
1. cookie 中缺少 max-age；expire 是服务器时间，无法保证服务器时间正确性。而且服务器时间时区字符串DST GMT的问题。
   总之 加max-age 解决大部分问题。之前的问题close了 不知如何reopen，重新提了。
  这个问题 个人觉得很重要，在gitee 上也提了，初始生产设备，时间需要页面配置，页面cookie不对，无法登陆，一个死循环的诞生。
2.  tcp listen ip地址无论设置什么都不变，只有端口生效。
3.  如何设置响应header，或改变header 内容？ 尤其cookie 上增加字段？

**Comment by CandyMi** [comment]
@suzaichuan  感谢您的反馈!  现在回答一下问题: 
 
  Q: `如何设置响应header，或改变header 内容？ 尤其cookie 上增加字段？`

  目前的`response headers`都是固定的,  目前也不考虑做特殊的定制化修改.

  Q: `tcp listen ip地址无论设置什么都不变，只有端口生效。`

  最新版的`TCP`内部仅可以指定`127.0.0.1`与`0.0.0.0`, 其它任何`string`参数等同于`0.0.0.0`.

  不知道上述是否能解决您的问题? 监听`动态`分配的`IP`地址不是必要, 所以您可以先测试一下?

  Q: `cookie 中缺少 max-age；expire 是服务器时间，无法保证服务器时间正确性。而且服务器时间....`

  `Coookie`组件缺少`max-age`是当初觉得`expire`已经足够, 能确定`max-age`可以解决`cookie`的问题那么本周末就可以加上.

**Comment by suzaichuan** [comment]
hi
1. cookie 加入max-age 可以解决firefox 的问题，火狐也没问题，而且超时时长也受控。
2.  tcp 地址的问题 
    设备有无线及lan 和wan 多接口，地址和端口确定的，如果0.0.0.0 其他接口的这个端口无法使用，尤其是 wan口与localhost 一一对应端口的。很多时候端口用了确定具体使用的比如80 http 443 https 5060 sip 2944 megaco 等等

**Comment by CandyMi** [comment]
@suzaichuan  好的!  `tcp`自定义监听地址与`Cookie`增加`max-age`的特性, 我将在本周末更新到`master`分支. 到时候麻烦您测试一下.

**Comment by CandyMi** [comment]
## 一、Cookie特性

![Cookie特性](https://user-images.githubusercontent.com/13453599/113256958-81154200-92fc-11eb-9ece-f7608b854a34.png)

## 二、TCP特性

---

```lua
local httpd = require "httpd"
local app = httpd:new()

-- app:listen("127.0.0.1", 9999)
-- app:listen("192.168.101.87" , 9999)

app:run()
```
![TCP端口](https://user-images.githubusercontent.com/13453599/113257222-dd786180-92fc-11eb-9300-8b8ea6ee95d0.png)

**Comment by CandyMi** [comment]
目前更新到主线分支, 如有问题请再次打开。  @suzaichuan
