### ISSUE TITLE
请教个路由的问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#24]
1. 同一个程序，连续listen 两个端口？怎么区分分别是哪个的路由？  注册路由无法分开，尤其是使用了admin的
    如果new 两个httpd ，分别启用，路由注册是否每个独立呢？ 两个httpd 要分别run 还是一次就可以？
2 . before 文档上描述是路由之前执行的，发现是路由了后才执行。没有注册路由永远执行不到。 有没方法实现真正的路由之前执行的呢？或统一的路由 比如 / 匹配所有。

**Comment by CandyMi** [comment]
@suzaichuan  感谢您的反馈, 这里回答一下您的疑问：

  * Q1: `同一个程序连续listen两个端口？怎么区分分别是哪个的路由？...`

      一个`cfadmin`进程只能监听一个普通端口(`Normal Port)、一个安全端口(`SSL Port`)、一个`Unixsock`套接字.

      之前并未考虑单进程的多实例需求，所以并未做不同实例的路由隔离. 这样做的原因也是不想让使用者在单个进程内使用多`Httpd`.

  * Q2: `before 文档上描述是路由之前执行的，发现是路由了后....`

      我认为`before`的准确意思是: "<b>找到路由之后</b>并在<b>调用回调之前</b>执行". 如果没有路由被注册, 那么跳过`before`的流程直接返回`404`属于正常的.

      在触发`before`回调之后，框架会为回调函数注入一个参数. 你可以根据传递的参数, 使用`string`库的<b>匹配模式</b>相关函数完成需求.

```lua
-- 如：
httpd:before(function(content)
  -- 所有以`/user`开头的路由都将匹配到
  if string.find(content.path, "^/user[/]?.*") then
    print(content.path)
    return 200
  end
  -- 所有以`/user`结尾的路由都将匹配到
  if string.find(content.path, ".+/user") then
    print(content.path)
    return 200
  end
end)
```

**Comment by suzaichuan** [comment]
@CandyMi 
 hi
   非常感谢！
   1. 如果启用tcp listen 或tcp connect 是否需要再次 cf_wait?如果只启用tcp 没http 时 不调用cf_wait 一段时间后coredump
   2. 误解了问题。
          主要想了解  没注册路由的请求怎么，回调自己的方法，或者怎么注册一个通用的路由，所有请求都能进入。
          另外before 既然找到了路由，进行处理就好了，效果不是一样的么，这个路由之前的意义应该不大吧？

**Comment by CandyMi** [comment]
@suzaichuan 

* Q1.  `如果启用tcp listen 或tcp connect 是否需要再次 cf_wait?如果只启用tcp......`

    这个要根据实际使用方法来决定需要怎么做，建议参考[httpd.init.lua](https://github.com/CandyMi/cfadmin/blob/master/lualib/httpd/init.lua)的代码.

* Q2.  `主要想了解 没注册路由的请求怎么，回调自己的方法.... 另外before 既然找到了路由，进行处理就好了....`

    之前由于一些特定的需求已经加入了`rest`规范的语法(可选)支持. 这样可以解决常用<b>路由匹配模式</b>的缺失问题.

    至于`before`设计, 它主要是在：中间件模块化、统一接入验权、第三方应用接入、自定义日志追踪等方面。

    `404`在`before`的优先级之前也是<b>特别优化</b>, 也是为了解决用户存在<b>把误用当特性</b>的特别情况。

**Comment by suzaichuan** [comment]
hi,
非常感谢！
临时用rest 方式确实可以实现，但存在一个问题，之前也提到过的Content-Type不能修改的问题。
1.上传下载处理，文件路径 和html所需一般不一致，通过路由处理的，返回类型不正确
2.js css 文件动态或redis等存储的，返回时类型不正确。这种比较常用的，nosql 存储网页
3.b2b 代理，比如远程抓取第三方页面处理。

**Comment by CandyMi** [comment]
@suzaichuan 

感谢您的建议, 这样能更好的帮助我改善框架.

但是由于您描述的问题设计的需求比较多, 建议您分离出不同的`issue`来进行提问. 这样我也能与您更好的沟通.
