### ISSUE TITLE
Content-Type 最好能修改

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#25]
hi
   简而言之，Content-Type 应该提供接口修改。
   因为：    
         1） rest 打开全部放过后（/{string[]:slist}），static就不会再生效了，需要自己去读取文件，读出内容返回 类型不能正确。
         2） 即使不用rest，需要读取的文件，可能httpc 或mq 等方式读取，必须不能进入static处理，这时类型也不能保证正确。
         为了实现这个目的，尝试了一种办法，也就是上一个问题——起两个实例的问题。既然不能使用两个实例，只能启用两个进程来处理，A B进程，A 收到请求，获取到数据，写文件到静态路径下，回响应给浏览器redirect（B），浏览器发起B请求，从静态文件下获取。 确实可以实现，但很麻烦，如果浏览器稍微严格一点，不同端口算跨域也就不行了。最好方法是可以修改Content-Type。 
          当然如果能 解决精确匹配路由和模糊匹配路由及staic的优先级，重定向也是一种办法。

**Comment by CandyMi** [comment]
@suzaichuan  感谢您的建议, 这边需要回应一下您的疑问:

* Q1: ` rest 打开全部放过后（/{string[]:slist}），static就不会再生效了，需要自己去读取文件，读出内容返回.....`

  针对这样的需求, 从框架内部是可以提供实现的 !  并且有一些社区的同学在业务中遇到了类似的问题. 

  但需要指出的是: 这样的`feature`即使从框架层面去优化,  对于`wrap_response`这种做法依然非常消耗资源!

**Comment by suzaichuan** [comment]
hi，
是的高性能是一方面，但有时无法避免的功能与性能的冲突。再者 怎么看静态存储问题，硬盘存储的性能是要低于内存的。很多数据是内存数据库存储的。他们的读取的open read close 是不一样的。框架中mq 可以对接redis 就可以起到这个作用。但目前看redis如果存储的是js或css 是无法完成的。

**Comment by CandyMi** [comment]
@suzaichuan  

目前我正在做内部测试, 如果没问题可以先放出来你们先使用.  但是一次修改可能无法做到比较完善.

最后我还是反对把`cfadmin`作为<b>文件管理器</b>, 毕竟它这方面做的肯定不会比专业工具要好.

: )

**Comment by CandyMi** [comment]
@suzaichuan 使用方法是这样， 应该能满足目前的需求了。 

```lua
local httpd = require "httpd"

-- 异常包装器
local http_throw = require "httpd.Throw"

-- 重定向包装器
local http_redirect = require "httpd.Redirect"

-- 响应包装器
local http_response = require "httpd.Response"
-- 磁盘文件类型
local file_response = http_response.file_response
-- 普通文本类型
local text_response = http_response.text_response

local app = httpd:new("App")

require "utils"

--[[ 访问：/error/内部服务器错误 ]]
app:use("/error/{info}", function (content)
  return http_throw(500, "错误: " .. content.query.info)
end)

--[[ 访问：/jump/www.baidu.com 重定向到`https://www.baidu.com` ]]
app:use("/jump/{url}", function (content)
  return http_redirect(301, "https://" .. content.query.url)
end)

--[[ 访问：/view/static/index.html 会响应`static`文件夹下的`index.html` ]]
app:use("/view/static/{name}.html", function (content)
  return file_response("static/" .. content.query.name .. ".html", "text/html")
end)

--[[ 访问：/static/welcome.html, 将会改编content-type为application/json ]]
app:use("/test/{id}", function (content)
  return text_response('{"id":[1,2,3]}', "application/json")
end)

app:enable_rest()
```

![image](https://user-images.githubusercontent.com/13453599/115352290-c89b3980-a1e9-11eb-8a79-061bc786e578.png)

![image](https://user-images.githubusercontent.com/13453599/115352320-cf29b100-a1e9-11eb-9389-dfb496b09565.png)


能协助测试一下这样的处理流程吗? 如果没什么问题， 本周末就更新到主线分支.

**Comment by suzaichuan** [comment]
hi，
  ok，我来测试看看。代码是新增么？ 分支dev 没看到差异。text_response，file_response 还没有

**Comment by CandyMi** [comment]
@suzaichuan 昨晚已经更新到测试分支

**Comment by suzaichuan** [comment]
@CandyMi 
    hi，分别测试了一下 两个接口。
1. file_response 设置fileinline 是可以读js css icon；如果不设置会弹出下载，是否具体能下载没测试。基本功能可用。
2. text_response 将js css 传入，回响应仅有5个头，js，css 等无法使用。如果在函数里修改添加Content-Disposition: inline，能识别，但发现最后两自己有丢失，是否必丢失没具体测试。转换 js css 有错误

**Comment by CandyMi** [comment]
@suzaichuan 

  您的描述没能提供示例与测试代码! 所以，我说一下我的理解 : )

  QA: `file_response 设置fileinline 是可以读js css icon；如果不设置会弹出下载，是否具体能下载没测试。基本功能可用。`

   从描述可以看出来, 您的问题已经解决了.     :)

  QA : `text_response 将js css 传入，回响应仅有5个头，js，css 等无法使用...`

  假设您说的将`js`/`css`传入指的是: "`js`或`css`文件内容传入到`text_response`内部, 将`application/javascript`和`text/css`传入到`ctype`代指的`content-type.`".  目前不仅可以支持js/css, 还可以支持json/xml/protobuf等等您自己指定的任意的`content-type`。
但框架目前不会检查传递的`content-type`是否有效, 所以这将需要使用者自行来解决正确性的问题.
  
  QA: `如果在函数里修改添加Content-Disposition: inline，能识别，但发现最后两自己....`

  `text_response`不会增加`Content-Disposition`头部, 并且我个人认为在`text_response`里这个头部的存在是没有意义的.

   所以您的描述让我比较疑惑, 所以想知道您是因为什么需求才觉得存在这个问题?

**Comment by suzaichuan** [comment]
hi
   是的 file_response  解决了。
   text_response  也正如你描述的一样，将js 内容字符串传入，测试上看 js css 内容到浏览器没有生效，也就是不能执行。加了一个字段Content-Disposition：inlne 发现，可以执行，只是执行错误，因为js不完整。具体原因我也不清楚。仅仅是一个现象。 测试用例就是 一个cf 转发到另一个cf 将读到响应再返回给第一个cf，使用text_response 转发内容。并不是我有Content-Disposition 的需求。

**Comment by CandyMi** [comment]
收到!

你可以使用我下面提供的示例代码进行测试.:

```lua
-- 访问：/test/1.html, 将会响应`text/html` 
app:use("/test/{id}", function (content)
  return text_response([[
    <html>
      <head>
        <script src="/static/1.js"></script>
      </head>
      <body>
      </body>
    </html>
  ]], "text/html")
end)

-- 访问：/static/1.js, 将会修改为: text/javascript 
app:use("/static/{id}.js", function (content)
  return text_response('console.log("Hello world")', "text/javascript")
end)
```

1. 直接访问: `/static/XXX.js`的时候, 浏览器<b>直接加载</b>后在`F12`开发者调试工具内的`type`永远是`document`.

2. 直接访问: `/test/1.html`的时候, <b>间接加载</b>`1.js`的时候能在·console`一栏就看到`hello world`的输出结果.

这个规则很早之前就存在了! 其本意为: <b>浏览器指定的脚本语言必须直接内嵌或者间接引用才可执行</b>.

所以正确的使用方法为：1. 写入到`html`的`script`标签内; 2. 使用标签进行外部<b>间接引用</b>

**Comment by suzaichuan** [comment]
好的，
多个js css 等类型可能会出问题。我继续测试看看。
之所以有这个疑问，，发现纯tcp 转发本身就有问题。
测试场景，cf1 cf2，浏览器访问cf1，cf1 转发到cf2，cf2 的响应由cf1 转发给浏览器。
cf1 程序会退出 [WARNING]: sub process 29654 exited with signal: ，大概率在welcom.html 或jquery.js 时退出。

```
local cf = require "cf"
local cf_fork = cf.fork
local tcp = require "internal.TCP"
local concat = table.concat

local function http_parse(msg)
	local hdr,body
	local p1,p2=string.find(msg,"\r\n\r\n")
	if(p2) then
		body=string.sub(msg,p2+1,-1)
		hdr=string.sub(msg,1,p2)
		
	else
		body=msg
	end
	return hdr,body
end
local function readall(fd,_size)
	local buffs=""
	while(1) do
		local buf=fd:recv(_size)
		if(buf==nil) then
			return nil
		end
		buffs=buffs..buf
		if(#buffs==_size) then
			return buffs
		else
			_size=_size-#buffs
		end
	end
	return nil
end

local function recv_http(fd,func)
        local buffs={}
	while(true) do
		local buf=fd:recv(4096)
		if(buf==nil) then
			print("close ",fd)
			break
		end
		buffs[#buffs+1] = buf
		local buffer = concat(buffs)
		--print(">>>>>>>>>",buffs[1])
		local hdr,body=http_parse(buffer)
		if hdr then
			print(hdr)
			local ctx_len,_=string.match(hdr,"Content%-Length:[%s]*([%w]+)\r\n")
			if(ctx_len==nil or #ctx_len==0) then
				ctx_len=0
			else
				ctx_len=tonumber(ctx_len)
			end
			local blen=0
			if(body) then
				blen=#body
			end
			if(blen==ctx_len) then
				func(fd,hdr,body)
				buffs={}
			elseif(ctx_len < blen) then
				print("error more -- no proc for test!!!")
			else
				local lefts=readall(fd,ctx_len-blen)
				if(lefts) then
					func(fd,hdr,body..lefts)
					buffs={}
				else
					break
				end
			end
		else
			print("???????????")
		end
	end
end
local function connect(addr,port)
	local sock = tcp:new():timeout(10)
	local ok, ret=sock:connect(addr, port)
	if not ok then
		print("connect err: ",ok,ret)
		sock:close()
		return
	end
	return sock

end

local function do_proc(fd,hdr,body)
	local sock=connect("**192.168.4.242**",80)
	print("connect",sock)
	print(hdr)
	sock:send(hdr..(body or ""))
	recv_http(sock,function(fdd,hhdr,bbody)
		--print(hhdr)
		fd:send(hhdr..(bbody or ""))
		sock:close()
		sock=nil
	end)
	if(sock) then
		print("close 2",sock)
		sock:close()
	end
	--tcp_client.close(sock)
end


local function dispatch(fd,ipaddr)
	print("dispatch",fd)
	recv_http(fd,do_proc)
	fd:close()
end


local function http_proxy(ip,port)
	local sock=tcp:new()
	local res=sock:listen(ip or "127.0.0.1", tonumber(port), function (s, ipaddr)
		if type(s) == 'table' then
			return dispatch(s,ipaddr)
		end
		return dispatch(tcp:new():set_fd(s):timeout(nil),ipaddr)
	end)
end
http_proxy("0.0.0.0",8082)
cf.wait()
```

**Comment by CandyMi** [comment]
@suzaichuan 

框架内部实现的`socket`是不可重入的, 所以直接引用内部的`对象`需要非常小心.

无论何时使用都建议您先参考一下已实现的内置库, 这样在使用的时候才能更具完备性.

最后建议您的<b>代码格式化</b>后发布出来，然后咱们就可以继续交流问题.

: )

**Comment by suzaichuan** [comment]
hi ,
   确实是参考httpd 和httpc 实现的测试。摘抄了部分代码，现象为第十个请求左右出现问题。socket是不可重入的 是指什么？每次启用都有new的，全新的socket建立。

**Comment by CandyMi** [comment]
`socket不可重入`指的是: 任何情况下只能在一个协程执行`connect`/`handshark`/`send`/`recv`等等网络操作.

**Comment by suzaichuan** [comment]
非常感谢，同时更糊涂了。
     1. tcp server 收到消息到通过client 发送，等待接收，再通过tcpserver 返回给浏览器整个过程，一气呵成，没任何切换协程动作。
     2.  如果上述有问题，那么httpd 路由处理里不能调用httpc 么？ 如果可以不是矛盾么？

**Comment by CandyMi** [comment]
# 伪代码示例

## 服务端示例:
```lua
-- 1. 首先创建服务端sock:
local s = sock:new()

-- 2. 然后使用s对象开始监听指定ip和port指定的地址与端口:
s:listen(ip, port, function(fd)
  -- fd为客户端的socket handle, 要配合socket对象使用.
  -- 1. 创建socket对象c, 并且吧fd添加到c对象内.
  -- 2. 使用创建Socket对象读、写客户端的消息.
  local client = sock:new():set_fd(fd)
  -- 发送消息
  client:send(data) -- data = 发送内容
  -- 接受消息
  client:recv(bytes) -- bytes = 字节数

  -- 关闭并释放fd
  client:close()
end)
```

## 客户端示例:

```lua
-- 创建sock对象.
local client= sock:new()

-- 建立连接
local ok, errinfo= client:connect(ip, port)
if not ok then
  return print(false, errinfo)
end
print("连接成功.")

-- 可能需要ssl应用层握手
-- sock:do_handshak()

-- 发送信息
client:send()
-- 接受信息
client:recv()

-- 关闭并释放fd
client:close()
```

**Comment by suzaichuan** [comment]
@CandyMi 
  非常感谢！
  我也是这样使用测试的。唯一不同的是，server 收到消息处理是tcp发出去。也就是消息驱动，再发送。和收到消息执行命令差不多。 是不是不能这样用，如果是那就意味着，httpd 和httpc 不能同时使用？

**Comment by CandyMi** [comment]
@suzaichuan 对于在`httpd`的`route`或者`before`方法内进行一次(或多次)转发`http`请求可以考虑使用`httpc`, 不建议自主实现一些不稳定的代替品.

**Comment by suzaichuan** [comment]
@CandyMi 
非常感谢！
 但不可避免的需要用tcp 或udp 来通信。 如果是route 里不能新的connect，http 做事务驱动除了做显示类的页面，其功能性东西很多完成不了了。那样的话cf 提供的 那么多库，就无法结合起来使用，限制了灵活性和多样性。

**Comment by CandyMi** [comment]
@suzaichuan 

如果是有单独的`tcp`与`udp`通信需求, 只要自行解决重入问题即可.  `tcp`与`udp`可以在任何地方使用.

我更有兴趣的是, 你多次提到想在内部使用`socket`. 是否有自定义网络交互协议的场景?

**Comment by suzaichuan** [comment]
@CandyMi 
    是的，http 只是个驱动，收到http 根据内容进行分发到不同的处理，有的重组http，有的udp，有的tcp，也有命令获取，也有mqtt，把结果组装后 http 回响应。udp tcp 内容自定义及其他标准协议。
    其本质都是一样的，http 处理时，受限所谓的tcp重入，popen 等操作无法进行，这个问题解决基本所有应用都可以无限制开发了。
    选用nginx，要加入cgi或uwgi才好做应用，虽然ngx lua也能做一些，但对通信实现不是很方面。 libwebsocket 库非常好，完全满足，但需要c 开发，很多页面的要去适配；后续维护不如lua方便，如果去封装lua，工作量也不小。 cf 正好提供了丰富接口，可以使用，目前看接口都是为httpd 使用的，做应用还是有难度，但做展示类web功能完全够了。

 能否自己解释一下tcp 重入问题的解决？ 我的例子也是照抄httpc的，为什么不行？究竟哪里重入了？自行解决要知道问题哪里冲突，才好处理。

**Comment by CandyMi** [comment]
@suzaichuan 

这边建议你给个崩溃的测试示例, 配上您的代码思路注释. 我们就可以根据情况讨论.

**Comment by suzaichuan** [comment]
实际使用，是http 根据url和body 发送tcp，或udp（面向连接的协议），等待响应，返回结果。为了简单不分析协议使用了以下测试方法（结果一样的错误）：
启动时 listen 8082端口，有新连接上来，调用 dispatch 开始收recv_http 消息； 收完整的消息  do_proc 处理（ 仿照httpd）；
 do_proc 处理方法是  
            连接 192.168.4.242 ：80 端口，将消息发送出去（仿照httpc）；
            然后等待响应； 收到响应后，再返回给浏览器

简单的测试，仅仅使用了http 协议。下面是完整的测试代码 。

```
local cf = require "cf"
local cf_fork = cf.fork
local tcp = require "internal.TCP"
local concat = table.concat
-- 将头 和 body 分离
local function http_parse(msg)
	local hdr,body
	local p1,p2=string.find(msg,"\r\n\r\n")
	if(p2) then
		body=string.sub(msg,p2+1,-1)
		hdr=string.sub(msg,1,p2)
		
	else
		body=msg
	end
	return hdr,body
end
--接收剩余长度 _size 消息
local function readall(fd,_size)
	local buffs=""
	while(1) do
		local buf=fd:recv(_size)
		if(buf==nil) then
			return nil
		end
		buffs=buffs..buf
		if(#buffs==_size) then
			return buffs
		else
			_size=_size-#buffs
		end
	end
	return nil
end
-- 接收http 消息，完成的http消息后 func 处理，一直收，除非退出或错误
local function recv_http(fd,func)
        local buffs={}
	while(true) do
		local buf=fd:recv(4096)
		if(buf==nil) then
			print("close ",fd)
			break
		end
		buffs[#buffs+1] = buf
		local buffer = concat(buffs)
		--print(">>>>>>>>>",buffs[1])
		local hdr,body=http_parse(buffer)
		if hdr then
			print(hdr)
			local ctx_len,_=string.match(hdr,"Content%-Length:[%s]*([%w]+)\r\n")
			if(ctx_len==nil or #ctx_len==0) then
				ctx_len=0
			else
				ctx_len=tonumber(ctx_len)
			end
			local blen=0
			if(body) then
				blen=#body
			end
			if(blen==ctx_len) then
				func(fd,hdr,body)
				buffs={}
			elseif(ctx_len < blen) then
				print("error more -- no proc for test!!!")
			else
				local lefts=readall(fd,ctx_len-blen)
				if(lefts) then
					func(fd,hdr,body..lefts)
					buffs={}
				else
					break
				end
			end
		else
			print("???????????")
		end
	end
end
-- 客户端连接服务器
local function connect(addr,port)
	local sock = tcp:new():timeout(10)
	local ok, ret=sock:connect(addr, port)
	if not ok then
		print("connect err: ",ok,ret)
		sock:close()
		return
	end
	return sock

end
-- 服务器收到消息处理，也就是 recv_http 回调 ；
-- 发送消息 到服务器，等待接收响应，接收后，发送给服务器，然后关闭本次连接（面向连接），退出客户端recv_http 接收
-- 本次消息处理完毕，服务端继续接收消息
-- 这里也尝试过fork 一个协程处理，效果一样有错误，后来去掉了。
local function do_proc(fd,hdr,body)
	local sock=connect("192.168.4.242",80)
	print("connect",sock)
	print(hdr)
	sock:send(hdr..(body or ""))
	recv_http(sock,function(fdd,hhdr,bbody)
		--print(hhdr)
		fd:send(hhdr..(bbody or ""))
		sock:close()
		sock=nil
	end)
	if(sock) then
		print("close 2",sock)
		sock:close()
	end
	--tcp_client.close(sock)
end


local function dispatch(fd,ipaddr)
	print("dispatch",fd)
	recv_http(fd,do_proc)
	fd:close()
end


local function http_proxy(ip,port)
	local sock=tcp:new()
	local res=sock:listen(ip or "127.0.0.1", tonumber(port), function (s, ipaddr)
		if type(s) == 'table' then
			return dispatch(s,ipaddr)
		end
		return dispatch(tcp:new():set_fd(s):timeout(nil),ipaddr)
	end)
end
http_proxy("0.0.0.0",8082)
cf.wait()
```

**Comment by CandyMi** [comment]
@suzaichuan 你的代码过于复杂, 事实上可以简单演示. 并且我没从你的代码中测试得到有效内容.

所以我决定提供了一份简单的代码演示如何解析协议: 

```lua
local cf = require "cf"
local LOG = require "logging"
local httpc = require "httpc"
local tcp = require "internal.TCP"

local function dispatch(sock, ip, port)
  -- 我们可以假设客户端会发送http协议, 我们解析完成然后发送一个自己构建的协议(http)到其他服务器(百度).
  -- 如果百度成功返回, 我们就返回百度的页面内容给他们.
  -- 我们可以假设客户端会发送http协议, 然后使用`readline`方法解析.
  local req = sock:readline("\r\n\r\n")
  if not req then
    -- 超时或断开了连接.
    return sock:close()
  end
  local method, path, version = req:match("([^ ]+) ([^ ]+) HTTP/([%d%.]+)[\r]?\n")
  if not method or not path or not version then
    -- 错误的协议
    return sock:close()
  end
  -- 打印出请求方法，路径，版本
  print(method, path, version)
  -- 读取HTTP协议头部信息
  local headers = {}
  for key, value in req:gmatch("([^ \r\n]+): ([^\r\n]+)[\r]?\n") do
    headers[key] = value
  end
  LOG:DEBUG(headers)
  -- 这里可以使用原始协议, 但是为了可读性我使用了内置库作为演示.
  -- 如果使用原始库, 就是先建立sock或ssl sock握手, 然后构造符合规范的http请求头部.
  -- 如果是自行定制的协议, 自行解决好连接和握手问题.
  local code, response = httpc.get("https://www.baidu.com/")
  if code then -- 如果请求成功返回内容
    sock:send(string.format("HTTP/1.1 200 OK\r\nServer: cfadmin\r\nContent-Length: %d\r\n\r\n", #response))
    sock:send(response)
  else -- 请求失败返回服务器500错误.
    sock:send("HTTP/1.1 500 server internal error\r\nServer: cfadmin\r\nContent-Length: 0\r\n\r\n")
  end
  -- 无论如何, 交互结束后都必须记得关闭连接.
  return sock:close()
end

local server = tcp:new()
assert(server:listen("0.0.0.0" or "127.0.0.1", 9999,
  function (fd, ip , port)
    -- 这里的fd是integer类型的文件描述符, ipaddr是端口
    -- listen_ssl才会返回构握手成功的socket对象.
    -- 需要创建socket对象并关联到已连接的fd上.
    local sock = tcp:new():set_fd(fd):timeout(15)
    -- 开始处理请求
    return dispatch(sock, ip, port)
  end)
)

cf.wait()
```

<b>不能在多个协程内调用同一个`tcp`或`udp`的`sock`(`connect`/`send`/`recv`/`sendfile`/`readline`)方法</b>.

下面再附上一个错误的示例应该是这样的:

```lua
while true do
  local data = sock:readline("\r\n\r\n")
  if data then
    print("失败")
    return sock:close()
  end
  -- 每次都创建一个协程写入数据
  cf.fork(function ()
    return sock:send(data)
  end)
end
```

上述操作可能会出现异常并且引起进程崩溃.

如果一定要多个协程操作写, 那么应该写成这样的:
```lua
local cf = require "cf"

local function dispatch(sock)

  local queue
  local sock_write = function (sock, data)
    if not queue then
      queue = {}
      cf.fork(function ()
        for _, buf in ipairs(queue) do
          sock:send(buf)
        end
        queue = nil
      end)
    end
    return table.insert(queue, data)
  end

  while true do
    local data = sock:readline()
    if data then
      print("失败")
      return sock:close()
    end
    sock_write(sock, data)
  end
end


dispatch(...)
```

至于方法也是同理,  不可将这种操作分开在多个协程.

**Comment by suzaichuan** [comment]
@CandyMi 
非常感谢耐心解答。
1.我的用法和你的描述完全一致，每次处理都是重新建立的socket 用完就close ，不会重复使用。如果用法正常，那么出现问题，可能就是真的问题了。
2.测试不出来是正常的，一次二次完全不会出现，一条一条测试也不会出现。之所以用http 转发测试就是为了模拟问题（仅是构造tcp测试例子，与http 本身无关），浏览器经过这个代理访问cf 页面（原版例子）；登录后大约第十个消息，welcome.html 或juery.js 的时候 出现，问题也是不固定在第几个消息上，目前看必现。

**Comment by CandyMi** [comment]
@suzaichuan 测试了几次都没复现, 你这边使用的是不是最新的代码呢？

**Comment by suzaichuan** [comment]
我用上个月的版本测试的。我再用最新的测试，更换操作系统 都试试。

**Comment by suzaichuan** [comment]
hi，
我用4.30 号代码。在ubutun 18 下测试 测试代码依然为已经贴出代码取名mt.lua。
./cfadmin -e script/mt.lua 登录后 程序退出 打印日志：
[WARNING]: sub process 28305 exited with signal: 139

换成 ubutun 16 也是一样，新旧代码，不同版本系统一样的错误。

添加http打印，由于打印特别多，最后一次交互打印为：
GET /lib/layui/lay/modules/jquery.js HTTP/1.1
Host: 192.168.4.216:8082
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
If-None-Match: 1234
Accept: */*
Referer: http://192.168.4.216:8082/admin/dashboard
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: CFLANG=323C59333D; CFTOKEN=5D454133460A1A1D522F415140211B575A2B1A7154585140795E1A265A42506B5344

**Comment by CandyMi** [comment]
你有尝试使用`CentOS 7+`的系统试过吗? 我没有可重现的测试代码可以定位你的问题.

**Comment by CandyMi** [comment]
并且我建议你在测试的时候可以把`logging`库内的`local ASYNC = true`这行代码注释掉.

**Comment by CandyMi** [comment]
```lua
-- 服务器收到消息处理，也就是 recv_http 回调 ；
-- 发送消息 到服务器，等待接收响应，接收后，发送给服务器，然后关闭本次连接（面向连接），退出客户端recv_http 接收
-- 本次消息处理完毕，服务端继续接收消息
-- 这里也尝试过fork 一个协程处理，效果一样有错误，后来去掉了。
local function do_proc(fd,hdr,body)
	local sock=connect("192.168.4.242",80)
	print("connect",sock)
	print(hdr)
	sock:send(hdr..(body or ""))
	recv_http(sock,function(fdd,hhdr,bbody)
		--print(hhdr)
		fd:send(hhdr..(bbody or ""))
		sock:close()
		sock=nil
	end)
	if(sock) then
		print("close 2",sock)
		sock:close()
	end
	--tcp_client.close(sock)
end
```

根据您的注释描述可能需要与第三方服务进行交互. 我建议使用`顺序`的方式编写代码, 而不应该使用回调方式来增加逻辑复杂度.

这里出问题的可能性比较大, 而且我无法得知任何您连接的目的. 这可能是造成问题的原因所在.

我还是强烈建议您看看我前面提供的那份实现代码,  并可以根据我提供的代码进行些许变更后再使用到您的代码中进行测试.

**Comment by suzaichuan** [comment]
hi
非常感谢！
仅仅为了测试tcp功能，为了方便，用http消息测试，http 服务端收，新建连接转发出去。 之所以用回调，因为消息分片了，一个完整的消息需要分多次接收，服务端是这样，客户端也是这样，这部分接收代码是相同的。
换成centos 7.01 版本测试，效果非常好。一直测试，登录注销，登录注销。。。
按照你的说法，修改了 服务端接收 和客户端接收不用公共函数，顺序执行。ubutun 也可以了不再出现崩溃。
非常感谢！！！
但存在一个问题就是如果将这个功能 附加到main.lua 相当于listen 两个。就会出现崩溃。目前看只能单独使用。

**Comment by CandyMi** [comment]
如果需要`listen`多个端口，那就`new`多个`sock server`实例.

**Comment by suzaichuan** [comment]
hi
   是的使用肯定是 多实例。不多实例 也没法监听多个端口啊。但只有一个cf.wait, 顺序启动，多个wait 感觉也没啥用。
  测试时实质只对第二个端口访问，tcp，转发出去。会出现程序崩溃。这个文件就是上面贴出的，把执行语句 注释掉，return 出去，在main 里require后调用执行语句。
如果单独执行第二个端口的文件，是ok的。
