### ISSUE TITLE
关于多库，分权分域的问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#26]
很多管理系统，数据需要隔离，有了个账套的概念。
比如 AB 两个应用，分别需要管理员admin@A admin@B；如果用admin的鉴权 ，登录后下一次访问无法知道是哪个库的。
  cookie加字段是可以的，这样每次处理是根据cookie 找数据库。 如果浏览器禁用cookie 怎么办？
是否有更好的方法实现？

**Comment by CandyMi** [comment]
@suzaichuan  

1. 权限的划分基于框架去做很难, 而自己设计业务权限就容易的多.

2. `Cookie`虽然在内部用作用户鉴权, 但是外部也可以做为开发者确认身份使用. 但`Cookie`被禁用那就无法使用`admin`库了.
