### ISSUE TITLE
后台操作耗时，如何同步？

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#27]
hi 
  之前提到过的一个老问题，popen 阻塞时，导致整个程序都阻住了，其他访问都不能进行，直到popen执行结束才能恢复。
  下面为测试代码，如果将fork 里执行换掉popen直接用cf.sleep 就可以。这是什么原因，对于执行时间过久的 怎么才能让出线程，让其他访问继续呢？  
```
app:use('/get',function(ctx, db)
        local res
          local co=cf.self()
        cf.fork(function()
                      local secondfile = io.popen([[sleep 10;echo "1234"]])
                      res = secondfile:read("*a")
                      secondfile:close()
                      cf.wakeup(co,res)
        end)
        cf.wait()
        print("res",res)
        return res
end)
```

**Comment by CandyMi** [comment]
@suzaichuan  

`io.popen`会启动一个系统级进程来完成指定的操作， 但是操作是否已经完成无从得知. 只能使用返回的`file`对象读取.

如需执行一个耗时较长的`file io`操作, 建议你可以到`lualib`内看看`aio`库来替代现有的`io`库.

它们不但有相似的Api让使用上简单上手, 而且在内部基于事件驱动重写过.  可以在非阻塞的情况下`同步执行`我们的耗时`IO`操作.

**Comment by suzaichuan** [comment]
hi
   对于执行系统命令并返回结果的，popen 是不二选择，即使用c写依然是popen。这个命令不仅重要而且常用。很多开源软件基于shell的，执行shell 脚本，又要同步，选取popen 是比较好的。 不在意执行时间的长与短，也没必要刻意的知道 多久才能返回。如果所有数据都是数据库，一切都不存在问题。关键很多数据 不是从数据库来的，是通过命令调用而来，尤其在设备上，几乎所有的数据都是命令获取。而命令获取与文件读写还是有区别的。
 上一个问题 给出测试代码就是tcp 网络获取http的，存在程序退出问题；本次测试 本机命令的。
 1.  换成c 写，在路由中 执行此功能应该也存在问题吧？
 2.  换成tcp 通信，外部的进程来实现此功能，cf等待返回值，好像和上一个问题一样，应该也存在signal 139 的问题
 对此 有没一种方案，处理过程移交出去，等待执行完毕再返回继续的操作呢？

**Comment by CandyMi** [comment]
根据您描述的popen场景. 这边的需求是不是可以理解成: 

  "执行任意一段`shell`命令, 但是不会阻塞当前进程. `shell`执行完成之后再框架会识别并自动返回?"。

**Comment by suzaichuan** [comment]
是的，就是这个意思。 就是最基本异步执行。将获取的数据正确的返回。同时不阻塞其他访问的工作。

**Comment by CandyMi** [comment]
之前做`aio`的时候有考虑提供`os.execute`的非阻塞版本, 但是之前感觉需求不是非常大.  : )

**Comment by suzaichuan** [comment]
@CandyMi 
    能否考虑加上去呢？
    我个人认为：
    从语言python，lua 等角度看，内部库都包含这命令运行。说明命令执行很重要。
     从框架角度看，一个框架，无法左右，业务的处理，而业务处理 很重要的一个就是命令调用。没有数据库连接正常，但没命令不正常。因为有命令可以外置数据库连接，开发者可以自定义做。
     从应用角度看：
            1. 设备上，cf最大优势是小巧，应用于设备非常方便，使用他，tcp http 都与了，业务，通信很容易上手。而设备上配置大多是命令提供的，比如uci ，shell，cli ，http 等。
            2. 服务器，除了一些运营服务，专用服务器，很大一部分都有和设备一样的功能，比如运营商的itms，各种bos系统。

**Comment by CandyMi** [comment]
@suzaichuan 非常感谢支持

我会持续跟进这个特性需求.  后期如果有需要, 我会回复此`issue`反馈进度并邀请您协助测试.

但目前这个需求不会在近期内完成, 我现在的主要工作还是在完成`http2`扩展协议支持上.

**Comment by CandyMi** [comment]
![image](https://user-images.githubusercontent.com/13453599/117610619-a36c6c00-b194-11eb-9741-766ba1487aca.png)


目前按照这种定义实现了一个版本, 不知道能不能满足您这边业务的需求.

**Comment by suzaichuan** [comment]
非常感谢！
如果合入和 我下载来测试看看。

**Comment by CandyMi** [comment]
@suzaichuan 

目前已经合并到`dev`分支, 如果有时间欢迎测试反馈结果.

**Comment by CandyMi** [comment]
@suzaichuan 

似乎这边已经没有问题, 日后欢迎继续打开`issue`反馈.    : D
