### ISSUE TITLE
升级后mysql连接错误

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#28]
hi
去年的版本，使用正常，从github上下载，重新编译安装后，发现mysql连接不上，回退正常。再次安装还是不行。
后来修改main.lua  mysql 连接localhost为127.0.0.1 ok。
最新代码应该有调整dns相关的处理，导致不能兼容。

**Comment by CandyMi** [comment]
可以检查一下`hosts`文件, 有可能是映射`localhost`域名写了`::1`.

**Comment by suzaichuan** [comment]
@CandyMi 
这不是重点，修改host 确实可以解决，改代码也能解决。
问题是老版本没问题，新版本 有问题，环境没做任何改变的情况下。

**Comment by CandyMi** [comment]
@suzaichuan 

框架使用`dual-stack socket`的特性来实现, `IPv4`与`IPv6`地址依赖在基础上才不会有兼容性的问题.

主要是新版本更看重的是对`dns`解析的兼容性考虑,  在不存在`localhost`的时候才会设置为`127.0.0.1`. 

无法否认的是`dns`还是存在一些`选择`上的问题, 但是修改`hosts`文件可以改善的话对大家来说可能是好事.

如果你有更好的看法或者建议也请尝试说服我  ：）

**Comment by suzaichuan** [comment]
hi
   我认为设计都不存在问题。尤其是全新的设计。
   只要说明 版本不兼容就可以了，否则升级了框架，用不起来，这个就很不友好了。

**Comment by CandyMi** [comment]
@suzaichuan  感谢建议, 之后会注意兼容性问题.
