### ISSUE TITLE
最新代码启动问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#29]
hi，
 主干上最新的代码启动 不能兼容之前的参数，-d需要创建logs 目录才支持-d参数，会大量的打印。 和之前提到localhost一样不能兼容。

**Comment by CandyMi** [comment]
@suzaichuan 收到!
看这边的提问, 应该是定制了框架的目录了是吧?  目前是准备修改`cfadmin`在后台运行时将`stdout`输出到指定文件. 
目前考虑是输出在`logs`目录下, 你这边如果在意兼容性的话我可指定到框架运行的根目录下面.

**Comment by suzaichuan** [comment]
@CandyMi 
是的 而且需要增加 LUAPATH LUACPATH   环境变量设置，运行在设备上，不需要记录运行日志，打印到串口就可以。默认没必要重定向到文件，如果需要 也可以将运行时重定向。

**Comment by CandyMi** [comment]
@suzaichuan 好的！ 现在基础功能应该可以满足业务上的需求了吧？

**Comment by suzaichuan** [comment]
@CandyMi
    非常感谢，基本可以使用简单替代uhttpd.
     由于加入了管理进程，运行时占用内存有点多。正常情况启动后cf会持续12k（RSS）内存增加。直到10M左右，停止增加。
这个管理进程既没有watchdog功能，也没网络或dns检测功能，意义不是很大。仅仅实现通信，很多方法，不需要常驻进程。

**Comment by CandyMi** [comment]
@suzaichuan  明白了. 你说的这个问题可以调整[这里](https://github.com/CandyMi/cfadmin/blob/master/lualib/logging/init.lua#L35)的大小来解决.

Edit: 在容量、内存比较敏感的情况下, 还是需要做一些内部修改的. 所以我也预留了这些配置.
