### ISSUE TITLE
是否有性能参考比较的数据呢

### ISSUE THREAD

**Issue by ljdog** [CandyMi/cfadmin#3]
类似muduo和其他几个开源库的比较

**Comment by ljdog** [comment]
类似muduo和其他几个开源库的比较

**Comment by CandyMi** [comment]
@ljdog
之前写过一些简单的测试脚本, 但是未做保存数据展示出来.
如果您有兴趣可以做一份较为详细的对比, 如果能发给我那就更好了！ 
我会考虑加入到wiki内.  : )

**Comment by CandyMi** [comment]
@ljdog 

[测试数据](https://github.com/CandyMi/core_framework/tree/master/lualib/admin)

这份数据是0.3RC的admin库测试数据, 未经过特殊的针对性优化.

按照实际验权逻辑角度出发, 包含了登录检查、用户信息获取、渲染页面等逻辑在内. (单核)

在经过负载均衡多实例运行/静态文件分离后实际并发性能会有数量级的提升. 单独作为接口开发的时候性能随业务情况会有增加与减少, 建议实际优化测试与优化

此数据仅作参考.
