### ISSUE TITLE
经由cfadmin 后台启动的脚本 或程序 信号量被屏蔽了

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#31]
hi
     后台调用脚本启动程序 无法kill 经定位发现屏蔽了信号量。
     之前代码 是ok的。 
BR

**Comment by CandyMi** [comment]
@suzaichuan  请给一个代码示例.

**Comment by suzaichuan** [comment]
@CandyMi 

app:api('/api/abc', function (content)
        os.execute("abc start &")
        return '{"code":0,"msg":"hello world"}'
end)
abc 为一个程序  killall abc 或者kill `pidof abc` 均不行，cfadmin -k pid 也不行

调试 日志（strace 程序 然后发送USR1 信号就可以看到mask）
--- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=4206, si_uid=0} ---
rt_sigreturn({mask=[HUP INT QUIT PIPE TERM TSTP]}) = -1 EINTR (Interrupted system call)

之前的没有管理进程是可以的。

**Comment by CandyMi** [comment]
@suzaichuan  下面一组路由应该可以实现"启动"和"杀死"进程的过程.

```lua
-- 启动
app:use('/ctrl/run', function (content)
  return string.format("%s, %s, %s", os.execute("sleep 100 &"))
end)

-- 杀死
app:use('/ctrl/kill', function (content)
  if content.args then
    return string.format("%s, %s, %s", os.execute(string.format("kill -9 %d", content.args.pid)))
  end
  return '{"code":200}'
end)
```

`/cfadmin -k cfadmin.pid`虽然也可以用做其他进程，但是并不是一定可以达到我们预期的效果 .   可以在`src/core_start.c`的`87`行查看源码可以得知我使用的是`SIGQUIT`.

我建议使用不可屏蔽的信号发送到指定进程, 这样可以保证对方无法屏蔽. 也可以等待我更新`aio.kill`方法后, 可以对指定进程发送指定信号掩码.

**Comment by suzaichuan** [comment]
@CandyMi 
    kill -9  强制杀死了，进程退出时需要做动作，不能强制。
    不在于是否加入 aio.kill, 实际场景，http 触发某个脚本，脚本里会 kill 。
     为什么之前的可以呢(没加入管理进程时)？ 程序启动时都存在signal_init  。目前想回退回去，找不到节点了。

**Comment by CandyMi** [comment]
@suzaichuan 

`os.execute`使用`system`来执行你的脚本, 而system会创建子进程来执行`cmd`命令. 

```lua
static int os_execute (lua_State *L) {
  const char *cmd = luaL_optstring(L, 1, NULL);
  int stat;
  errno = 0;
  stat = system(cmd);
  if (cmd != NULL)
    return luaL_execresult(L, stat);
  else {
    lua_pushboolean(L, stat);  /* true if there is a shell */
    return 1;
  }
}
```

`cfadmin`的注册信号无关父子继承, 而是取决于业务是否需要. 比如: 使用`httpd`服务就会注册信号.

前面所述的程序应该是注册了`特殊`的信号来解决`安全退出`的问题, 这更需要自行设置信号并且由`aio.kill`来指定信号掩码.

**Comment by suzaichuan** [comment]
@CandyMi 
   system popen 都是一样的，实际都是fork，如果不特别设定都会继承父进程信息。遇到过很多了socket 啥的都会被继承。
uhttpd 的做法是ubus或rpcd 执行命令（消息通知），也就是第三方程序；如果用crontab，但不实时，但能解决停止程序的问题。 我用之前的版本反复测试了，确实可以，效果非常很好没，暂时先回退回去，至少不影响使用。 这次切换成新的，为了使用添加的新功能，确实冒进了，localhost, logs 目录，及杀不死问题，不确定的问题不知是否还存在，先回退使用了

**Comment by CandyMi** [comment]
@suzaichuan  OK, 明白您的问题了. 那是否重置子进程的信号掩码后您这边就可以正常了呢?

**Comment by suzaichuan** [comment]
@CandyMi 
     貌似不行，在work_run 函数里重置了信号量也不行。估计得用libev 提供的函数才行，或者其他地方。
     理想做法 fork 时做此功能。 然而，   回退的版本，存在内存一直增长的情况(16k)，即使不使用。但最新的增长到10M 可以稳定。
      建议还是去掉多进程的处理，正常用不到，如果用的话，一般前面会有nginx，直接多起几个进程，也是很好的。libev 小巧的优势应该保持。大型应用使用多个进程而非多进程 解决方案就行了，因为大型设备，服务器，不在乎小，更不在乎内存，硬盘；框架也满天飞，更快速开发语言选择也更广泛。相反，小型的，需要考虑体积，内存，稳定等情况很少。更何况cfadmin在大型应用中作为一个组件就是非常合适的。如果需要手动调优，比如把中断 绑定到某cpu，处理放在另一个cpu，实际情况不足一而论。所以个人建议，保留原有的一个进程处理非常好。

**Comment by CandyMi** [comment]
@suzaichuan 上个月中旬开始已经改为：不指定`-w` 大于1的参数的情况下不会启动管理进程模式.

**Comment by CandyMi** [comment]
@suzaichuan 

如果有时间可以使用最新版本的`aio.popen`、`aio.kill`测试是否能满足需求?

`aio.kill`的可选信号指定与`aio.popen`的子进程属性独立与清除父进程的继承信号与会话.

**Comment by CandyMi** [comment]
@suzaichuan 

`建议还是去掉多进程的处理，正常用不到，如果用的话，一般前面会有nginx，直接多起几个进程，也是很好的。libev 小巧的优势应该保持。大型应用使用多个进程而非多进程 解决方案就行了，因为大型设备，服务器，不在乎小，更不在乎内存，硬盘；框架也满天飞，更快速开发语言选择也更广泛。相反，小型的，需要考虑体积，内存，稳定等情况很少。更何况cfadmin在大型应用中作为一个组件就是非常合适的。如果需要手动调优，比如把中断 绑定到某cpu，处理放在另一个cpu，实际情况不足一而论。所以个人建议，保留原有的一个进程处理非常好。`

 这个观点我是非常认同的, 甚至我也在不断对框架进行优化的途中也有很多思考:

  1. 之前因为不断优化性能在业务上带来了更多的应用场景, 在稳定性与可控性上却反而降低了.

  2. 尽可能的兼容更多的业务场景并且逐渐替代它们, 让更有优势脚本语言来展现应有的优势.

  3. 收集的不同场景的业务反馈还是较少,  所以只能按照目前已有的项目上不断迭代特性.

**Comment by suzaichuan** [comment]
@CandyMi 
    希望越来越好！
    尝试用aio.popen ，今天20210702 代码，无法执行。最简单的echo “111111" 都无法执行
    添加打印看到错误： false   **attempt to call a nil value**     echo "11111">/tmp/kkkk

**Comment by suzaichuan** [comment]
@CandyMi 
      makefile 书写 有一些问题，需要调整 搜索路径不应该存在 -L/usr/lib 类似这样的。编译链工具会自己查找，CFLAGS 传入。
修改编译后可以运行 aio.popen与直接调用os.execute 的效果是一样的。虽然mask 里没有TERM 但也多次很多不常用的信号量。程序依然捕获不到，杀不死。
       laio_popen::command /etc/initscripts/xl2tpd.sh restart &
     Process 31305 attached
select(5, [3 4], NULL, NULL, NULL)      = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=31507, si_uid=0} ---
sigreturn() (mask [ILL ABRT FPE USR1 CHLD TSTP TTIN TTOU URG XCPU VTALRM PROF IO PWR RTMIN]) = -1 EINTR (Interrupted system call)

   只启用一个进程，但效果和以前不一样，同样杀不死，但 在work_run 函数里加清除term等信号量，就可以杀死了。应该还是哪里有差异了导致的。

**Comment by CandyMi** [comment]
@suzaichuan 

你的提议让我今天发现了一个隐秘的内存泄漏与多次链接`libev`导致的静态地址映射问题.

我稍后再提修复`commit`, 你有时间的话可以帮我断点测试一下问题.

**Comment by CandyMi** [comment]
@suzaichuan 

使用`aoi.popen`时候, 如果cmd内部加上`&` 会导致框架获取的进程ID不一致, 所以可能导致无法退出的情况.

**Comment by suzaichuan** [comment]
@CandyMi 
      好的我来测试看看内存情况。 之所以& 后台是因为 会阻塞。新增了一个aio.execute 也试了 ，结果一样的。daemond =1去掉&，也阻塞住进程，kill 同样杀不死。
core.c 中 work_run 的signal_init 注释掉 不需要aio 也是可以杀死进程的。
	if (status == LUA_YIELD)
	  signal_init(NULL);

**Comment by CandyMi** [comment]
@suzaichuan  

用到守护进程的时候， `daemond`参数必须为true. 例如: "sleep 100 &". 

非守护进程则不需要理会这个值.

**Comment by suzaichuan** [comment]
@CandyMi 
   是的，总之如果不修改 代码，去除work_run  中的signal_init，不管用aio 还是其他方式，都是不能正确的kill cfadmin 启动的程序。

**Comment by CandyMi** [comment]
@suzaichuan 那就奇怪了, 我这边最新版本的代码已经可以了. 您这边有没有可能更新后未重新编译或测试不完善呢？

**Comment by suzaichuan** [comment]
@CandyMi 
    今日重新下了代码编译，还是一样的，使用和不使用aio 都不能kill。
你是如何测试的？我没有使用aio.kill ,因为是外部kill的。
  内存从现象观察，和之前一样。增到到10M 左右，稳定下来。

**Comment by CandyMi** [comment]
@suzaichuan  抱歉回复较晚.

最近根据您提到的问题对`aio.popen`与`aio.kill`方法修改了多次, 但是最终发现其中一部分问题并不在框架本身. 

这边先说一下目前的修改:

1. 默认情况下, 框架单进程执行不会创建守护进程. 减少内存占用与调试复杂度.

2. 关于"子进程继承文件描述符"的问题， 在最新的版本中我已经修复. 可以从[这里](https://github.com/CandyMi/cfadmin/blob/master/src/core_sys.h#L64)看到.

3. 内存占用的问题可以通过设置[这里](https://github.com/CandyMi/cfadmin/blob/master/lualib/logging/init.lua#L34)来减少低配设备的内存占用问题.


  最后回复一下您提到的关于 "无法杀死 `cfadmin`创建的子进程"的问题!

  这是因为子进程在通过`exec`函数调用`/bin/sh -c `执行后再次使用`&`或者调用`fork/daemon`进入到守护进程模式. 经过多次测试后发现, 这种情况下创建的进程是已经不归属`cfadmin`管理. 虽然我可以通过计算父进程的`PID`的偏移值(`offset`)的方式计算出生成的子进程的`PID`, 但即使正确的子进程`PID`也无法监听到它的`退出事件`. 

昨晚的深思熟虑后还是决定在`aio.popen/aio.execute`放弃这个功能, 但是还会保留支持基本的`command`.

不过据我所知可以在业务层面上完成，毕竟可选的解决办法很多！ 如： `at`定时任务等.

以上.

**Comment by suzaichuan** [comment]
@CandyMi 
  从使用场景上来说：
      使用cfadmin 最主要的一个功能就是配置管理。配置管理，基本应用场景就是用户点击按钮下发配置，然后后台使之应用生效。而这个应用生效一般都是调用命令（比如恢复出厂），这个命令就包括有一种启动，停止程序的功能。
     所以说不在于增加所谓的新功能，而在于 是否有必要而且必须屏蔽TERM kill 信号量，一般情况下外部信号也就是ctl+c。如果非必须，可以考虑将term信号量放过。

**Comment by CandyMi** [comment]
@suzaichuan

最新版的代码使用`cfadmin`启动后, 测试外部使用`kill SIGTERM`信号是可以正常退出的.
