### ISSUE TITLE
发现一个稳定性的随机问题

### ISSUE THREAD

**Issue by suzaichuan** [CandyMi/cfadmin#32]
hi
     设备一直运行，大约30台，发现有1-2台设备页面连不上，查询进程死掉了。
     查看日志，没报错误，具体原因尚不明确。 手动拉起来，跟踪，发现有的啥也不操作也会退出进程。
     由于随机性的，很难确定，也很难发现，但由于设备多，出现了几次，才确认有这个问题。
     
     估计短期无法定位，暂时外部加了watchdog，定时扫描程序健康检查。不由得想起之前提的问题，popen 信号屏蔽及多进程的，建议一个方案：
      可选启动管理进程，管理进程做watchdog，根据参数 检查健康，检查网络，检查dns；负责执行popen，system 命令。
      子进程处理http 消息，如果后台执行系统命令 提供执行系统命令接口【发送消息给管理进程去执行（如果没有管理进程，保持原样）】；
       这样 所有问题基本都解决了，而且起到意外或其他情况导致程序挂掉，迅速拉起来。
BR

**Comment by CandyMi** [comment]
感谢反馈: 
   * 这边建议使用设备数据主动推送模式 + 业务流程功能日志定位问题所在, 这样复现问题的几率较大.
   * 关闭编译优化并且加上`-g`等参数生成`coredump`, 查看调用栈也可以确定问题出现在哪部分代码上.

**Comment by CandyMi** [comment]
@suzaichuan  您描述的问题还有在测试吗?

**Comment by suzaichuan** [comment]
@CandyMi 
   一直再测试，发现x86 下偶尔也会出现，可能几个礼拜出现一次。

**Comment by CandyMi** [comment]
@suzaichuan 
可以在运行期间发送一个`SIGPIPE`来测试是否信号的问题.

**Comment by CandyMi** [comment]
这边我先关闭`issue`, 后续有其它进展请继续回复.
