### ISSUE TITLE
建议httpd增加DELETE和PATCH动词的支持

### ISSUE THREAD

**Issue by Nuctori** [CandyMi/cfadmin#36]
cfadmin的设计思路中，似乎是推荐使用rpc的风格设计接口。
但是也必然存在需要设计restful风格接口的场景，（比如公司项目规范规定）
我寻思应该增加DELETE和PATCH动词的支持，以支持此类需求

**Comment by CandyMi** [comment]
@Nuctori 
好建议, 可以提个PR增加支持.
