### ISSUE TITLE
大哥，AES_256_GCM加密可以用吗

### ISSUE THREAD

**Issue by walking-with-linght** [CandyMi/cfadmin#38]
`# -*- coding=utf8 -*-
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import hashlib,,cryptography.exceptions
import base64

def decrypt(key,nonce, ciphertext, associated_data):
    print(key,nonce, ciphertext, associated_data)
    key_bytes = str.encode(key)
    nonce_bytes = str.encode(nonce)
    ad_bytes = str.encode(associated_data)
    data = base64.b64decode(ciphertext)
    aesgcm = AESGCM(key_bytes)
    ret_str = aesgcm.decrypt(nonce_bytes, data, ad_bytes)
    print(ret_str)

def encrypt(key,nonce, ciphertext, associated_data):
    print(key,nonce, ciphertext, associated_data)
    key_bytes = str.encode(key)
    nonce_bytes = str.encode(nonce)
    ad_bytes = str.encode(associated_data)
    aesgcm = AESGCM(key_bytes)
    ret_str = aesgcm.encrypt(nonce_bytes, ciphertext, ad_bytes)
    print(base64.b64encode(ret_str))#加密后未将ad_bytes拼接，有些加密函数会拼接起来

if __name__ == '__main__': 
    if sys.argv[1]=="en":
        encrypt(sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5])
    elif sys.argv[1]=="de":
        decrypt(sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5])
        `
这是python加解密的代码
这是数据

明文
THIS_IS_SUCCESS_DATA

key
jysng121054180907654321741852963

随机字符串
qKJB3l8rkNEF

aad(附加数据包) 
test_aad

加密
python aead_aes_256_gcm.py en jysng121054180907654321741852963 qKJB3l8rkNEF THIS_IS_SUCCESS_DATA test_aad

解密
python aead_aes_256_gcm.py de jysng121054180907654321741852963 qKJB3l8rkNEF PD4m3fac6rXLqEspUpR9Sv/3S+F/4e/fHWssMz8SY9EIJ6Mo test_aad

可以用你的库么...

**Comment by CandyMi** [comment]
看你的意思是想使用`cfadmin`的内置crypt库来完成`aes_gcm`的加、解密?

实现需要一点时间, 这边急着使用吗?

**Comment by walking-with-linght** [comment]
是的，不急，我等你 (*^▽^*)

**Comment by walking-with-linght** [comment]
以下为python生成的十组加密后的数据，已验证可正常解密

明文:   random_data1
随机字符串:     351976040480
key:    93808881865549431718639935443393
aad:    random_aad1
加密后: gaVJ7DyTdXBR/jwU0dgX52As0OSKs4aolrMbEA==

明文:   random_data2
随机字符串:     007685851800
key:    08864373125554693552942566452433
aad:    random_aad2
加密后: S9rPjGxkCw6yu+OHdak1CyeJYvydYcEOfGH5gA==

明文:   random_data3
随机字符串:     996486483918
key:    07379625863106158912351048570093
aad:    random_aad3
加密后: 2yvOrfcH0cVSv/kFePP2zl7A5I2DiFK5Qp9kWA==

明文:   random_data4
随机字符串:     522317832029
key:    00973903319548176493394000980779
aad:    random_aad4
加密后: NXkpmMRGM15UUzCCykAlAXPiPSri8IT5Bov5wQ==

明文:   random_data5
随机字符串:     948812029390
key:    30315389832153944787324897128698
aad:    random_aad5
加密后: V9zvD8vKIdfgglvlZ+IMfTiWWiFsE362eq+jig==

明文:   random_data6
随机字符串:     427390202635
key:    92958274971032621646580156304675
aad:    random_aad6
加密后: UszTJ95ylNyR7iRkIJG7MdhIrknJcWUiLsknoA==

明文:   random_data7
随机字符串:     936182554191
key:    51887612219173807927681514014124
aad:    random_aad7
加密后: zbPywbLlYjL6qUf306CbABewhYagQUBXGCCzXg==

明文:   random_data8
随机字符串:     694159975112
key:    92403257373765087567368945282584
aad:    random_aad8
加密后: 4x2MPnCJgsVVohV0q+eVK2PQNUWc+pgBoEWr1A==

明文:   random_data9
随机字符串:     863581045678
key:    42616699931058075510139659727217
aad:    random_aad9
加密后: zF+VatrO7N+zRcyU+LpRlYqq2gELtduv4VWrmQ==

明文:   random_data10
随机字符串:     293388286595
key:    75800282826999829122255589639531
aad:    random_aad10
加密后: 79P4I5HcKc3cDEF4oX63+oheOtVGjci0OQT35Zk=
