### ISSUE TITLE
能否把libev 整合到代码里面去呢 

### ISSUE THREAD

**Issue by ljdog** [CandyMi/cfadmin#4]

**Comment by CandyMi** [comment]
@ljdog
暂时不考虑整合lua、libev等库， 这样对版本选择限制会少一些 :)

**Comment by ljdog** [comment]
@CandyMi 
采用git submodule的方式呢  我感觉云风那种自带库 直接拉代码就能编译的方式很酷

**Comment by CandyMi** [comment]
@ljdog 
最早期的版本我曾经将ev、je都联合整合编译, 因为那段时间修改了一定ev的源码.
但是最后发现无非就是一个整合的bash脚本集.
现在的makefile中定义的非常明确, 想用je或tc都只是一个注释掉问题.
lua5.3除非以后需要修改一定实现, 否则达到的效果不如skynet修改了lua源码的实现那么大必要. :)
