### ISSUE TITLE
support https

### ISSUE THREAD

**Issue by gcclua** [CandyMi/cfadmin#5]
hi, 
       how to config https support ? 

         nice

**Comment by CandyMi** [comment]
@gcclua 
Just use it like this:
```lua
httpc.get("https://domain:port/path/to")
```
Internally judged automatically protocol :)

**Comment by CandyMi** [comment]
if your domain port is `80` or `443` ,  You can ignore the port option.

**Comment by CandyMi** [comment]
@gcclua 
If you are referring to the server side support `https`, `cf` supports any load balancing agent tool.
