### ISSUE TITLE
http file upload example

### ISSUE THREAD

**Issue by gcclua** [CandyMi/cfadmin#6]
Hi,
        where can i find example about file upload for the cf framework
  
             thanks

**Comment by CandyMi** [comment]
Hi.
When there is one (or more) files uploaded via the HTTP interface(`use` or `api`), HTTP `content` will have a `files` field to indicate that there is a file upload. You can easily determine if there is a `files`.

Note that it will be an array of type `table`.  Each `item` of `files` will have 2 fields: `filename` and `file`. `filename` is the file name, `file` is the file content. You can try to modify and use the `POST_FILE.html` file to test file uploads. :)

Unfortunately, there is no documentation detailing it now. If you still have questions, you can continue to add it.

**Comment by gcclua** [comment]
> Hi.
> When there is one (or more) files uploaded via the HTTP interface(`use` or `api`), HTTP `content` will have a `files` field to indicate that there is a file upload. You can easily determine if there is a `files`.
> 
> Note that it will be an array of type `table`. Each `item` of `files` will have 2 fields: `filename` and `file`. `filename` is the file name, `file` is the file content. You can try to modify and use the `POST_FILE.html` file to test file uploads. :)
> 
> Unfortunately, there is no documentation detailing it now. If you still have questions, you can continue to add it.

thanks 
      so the file's content upload to lua table as string ?  or store as a temp file ? if binaray file should how to handle, and what is the file size limit ?

**Comment by CandyMi** [comment]
@gcclua 

> thanks
so the file's content upload to lua table as string ? or store as a temp file ? if binaray file should how to handle, and what is the file size limit ?

`cf` doesn't care if the file is plain text or binary. So, the contents of the file will be stored as strings in `files`, which may be plain text or binary.

You can judge based on the `filename` field, which usually contains the suffix of the uploaded file.

The file content size limit is limited by the `httpd:max_body_size` method. It is not recommended to upload files larger than 100K at one time.
