### ISSUE TITLE
httpc client 

### ISSUE THREAD

**Issue by gcclua** [CandyMi/cfadmin#8]
Hi, CandyMi
the Httpc can not fetch from many web support User-Agent check, or Accept-Encoding compress  
"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11\r\n" 
Accept-Encoding: gzip,deflate

**Comment by CandyMi** [comment]
Although `trunked` is currently supported, it is limited to `identity`.
If you test your own web server, you can try to turn off the gzip function of the web server.
