### ISSUE TITLE
how to handle image cache ?

### ISSUE THREAD

**Issue by gcclua** [CandyMi/cfadmin#9]
Hi, CandyMi
     what is the default way that handle image cache in core framework, the png number over 10 will cause so slow to replay, if use the thirty cache, how to integrate ?

**Comment by CandyMi** [comment]
@gcclua 
For example: You want to download a cached static file (js/css/png) when the browser first accesses the cf web server. It can be read locally when the second access is made, right?

I am not sure if I know what you mean.

**Comment by gcclua** [comment]
yeah, I mean first accesses is too slow, about use 7~8 second to load 10 png, disk read problem

**Comment by CandyMi** [comment]
If the disk itself is slow to read, I recommend that you migrate the static files to a separate server. This will alleviate this problem.

Although cf can notify the client to cache static files, this can not solve the problem of low efficiency of the disk itself.

**Comment by CandyMi** [comment]
@gcclua 
If the static file read speed is normal, we can set the `ttl` parameter of the `httpd:static(folder, ttl)` method, so that each client does not need to request it again during the `ttl` period after the last request for the static file.

**Comment by gcclua** [comment]
I want to find a way,   set framework to cache some png into server's memory,  keep about 10240 png that will be frequent access

**Comment by gcclua** [comment]
If httpd server preload/cache static folder that user set before bootstrap, and check cache when receive the hit request for the cache url/image,

**Comment by CandyMi** [comment]
@gcclua 
`cf` does not implement this feature, you can only try other ways. : )

**Comment by CandyMi** [comment]
@gcclua 
On the `dev` branch, I try to use 'sendfile' to improve the performance of the file being sent. Using `zero-copy` may be better than the original implementation.

I don't know if this will help you solve the problem you're experiencing, but at least it will effectively reduce the memory fluctuations caused by sending `Lua` large files.

If you have time, you can try to pull the `dev` version for testing.

**Comment by gcclua** [comment]
OK,thanks,I will try
